export type CrmLocale = "en" | "fr";

export const CRM_LOCALE_STORAGE_KEY = "bopoil-crm-locale";

const french: Record<string, string> = {
  "Good morning": "Bonjour",
  "Run every appointment from one calm workspace.": "Gérez chaque rendez-vous à partir d’un espace de travail simple et calme.",
  "Salon calendar": "Calendrier du salon",
  "A seven-day view of staff capacity and pet flow.": "Une vue sur sept jours de la capacité de l’équipe et du parcours des animaux.",
  "Priority waitlist": "Liste d’attente prioritaire",
  "Recover demand the moment a safe opening becomes available.": "Récupérez la demande dès qu’une plage sécuritaire se libère.",
  "Every relationship, preference, and visit history in one place.": "Toutes les relations, préférences et visites au même endroit.",
  "Keep every touchpoint warm, timely, and traceable.": "Gardez chaque échange chaleureux, ponctuel et traçable.",
  "Shape your menu, timing, deposits, and online availability.": "Configurez vos services, durées, acomptes et disponibilités en ligne.",
  "Your team": "Votre équipe",
  "Keep skills and working hours aligned with the booking calendar.": "Alignez les compétences et les heures de travail sur le calendrier des rendez-vous.",
  "Workforce & payroll": "Main-d’œuvre et paie",
  "Track time, approve work, and prepare a traceable gross-pay handoff.": "Suivez le temps, approuvez le travail et préparez un transfert de paie brute traçable.",
  "Inventory & purchasing": "Inventaire et achats",
  "Know what is on the shelf, what it costs, and what needs ordering.": "Sachez ce qui est en stock, ce que cela coûte et ce qu’il faut commander.",
  "Finance & books": "Finances et comptabilité",
  "Keep every sale, expense, receipt, tax amount, and closeout traceable.": "Gardez chaque vente, dépense, reçu, taxe et clôture traçable.",
  Reports: "Rapports",
  "See the operational signals behind a healthier salon.": "Consultez les indicateurs opérationnels d’un salon en meilleure santé.",
  "Salon settings": "Paramètres du salon",
  "Shape the business, booking rules, access, and every location.": "Configurez l’entreprise, les règles de réservation, les accès et chaque emplacement.",
  "Live salon workspace": "Espace de travail du salon en direct",
  Today: "Aujourd’hui",
  Calendar: "Calendrier",
  Waitlist: "Liste d’attente",
  "Clients & pets": "Clients et animaux",
  Messages: "Messages",
  Services: "Services",
  Team: "Équipe",
  Workforce: "Main-d’œuvre",
  Inventory: "Inventaire",
  Finance: "Finances",
  Intelligence: "Analytique",
  More: "Plus",
  Settings: "Paramètres",
  "Add another salon": "Ajouter un autre salon",
  "View storefront": "Voir la vitrine",
  "Add team member": "Ajouter un membre",
  "New appointment": "Nouveau rendez-vous",
  "Salon workspace": "Espace du salon",
  "Loading location…": "Chargement de l’emplacement…",
  "We couldn’t load the salon yet.": "Le salon n’a pas pu être chargé pour le moment.",
  "Try again": "Réessayer",
  "Workspace controls": "Commandes de l’espace de travail",
  "Close workspace controls": "Fermer les commandes de l’espace",
  Location: "Emplacement",
  Salon: "Salon",
  "Sign out": "Déconnexion",
  "Current salon": "Salon actuel",
  "Current salon location": "Emplacement actuel du salon",
  "Salon navigation": "Navigation du salon",
  "Enter your authorized salon email. We’ll send you a private, one-time sign-in link.": "Entrez l’adresse courriel autorisée du salon. Nous vous enverrons un lien de connexion privé à usage unique.",
  "That link has expired or was already used. Request a new one below.": "Ce lien a expiré ou a déjà été utilisé. Demandez-en un nouveau ci-dessous.",
  "Email sent": "Courriel envoyé",
  "Send secure link": "Envoyer un lien sécurisé",
  "Sending…": "Envoi…",
  "Check your inbox. For privacy, we show this same message for every address.": "Consultez votre boîte de réception. Pour protéger la confidentialité, ce même message s’affiche pour toutes les adresses.",
  "The email could not be sent. Please try again.": "Le courriel n’a pas pu être envoyé. Veuillez réessayer.",
  "Local preview only—open the complete owner workspace without sending an email.": "Aperçu local seulement — ouvrez l’espace complet du propriétaire sans envoyer de courriel.",
  "Opening workspace…": "Ouverture de l’espace…",
  "Open demo owner workspace": "Ouvrir l’espace de démonstration du propriétaire",
  "Back to BOPOIL": "Retour à BOPOIL",
  "Your salon operating system": "Le système d’exploitation de votre salon",
  "Create the home for your bookings, care records, team, payments, and client relationships. You can fine-tune every detail after setup.": "Créez l’espace central de vos réservations, soins, équipe, paiements et relations clients. Vous pourrez ajuster chaque détail après la configuration.",
  "Salon and location created": "Salon et emplacement créés",
  "Starter services added": "Services de départ ajoutés",
  "Booking workspace ready": "Espace de réservation prêt",
  "Salon setup": "Configuration du salon",
  "Tell us about your first location": "Parlez-nous de votre premier emplacement",
  "This takes about two minutes.": "Cela prend environ deux minutes.",
  "Back to workspace": "Retour à l’espace de travail",
  "Salon name": "Nom du salon",
  "Location name": "Nom de l’emplacement",
  "United States": "États-Unis",
  "Street address": "Adresse civique",
  Province: "Province",
  State: "État",
  "ZIP code": "Code ZIP",
  "Salon phone": "Téléphone du salon",
  Timezone: "Fuseau horaire",
  Eastern: "Est",
  Central: "Centre",
  Mountain: "Rocheuses",
  Pacific: "Pacifique",
  Atlantic: "Atlantique",
  "Creating your salon…": "Création de votre salon…",
  "Create my salon →": "Créer mon salon →",
  "Your workspace stays private. You’ll invite your team when you’re ready.": "Votre espace reste privé. Vous inviterez votre équipe lorsque vous serez prêt.",
  "All appointments": "Tous les rendez-vous",
  "Active requests": "Demandes actives",
  "Appointments": "Rendez-vous",
  "Appointment": "Rendez-vous",
  "New client": "Nouveau client",
  "Existing client": "Client existant",
  "Client & pet": "Client et animal",
  "Client & pet directory": "Répertoire des clients et animaux",
  "Client name": "Nom du client",
  "Client photos": "Photos du client",
  "No matching clients": "Aucun client correspondant",
  "No photos yet": "Aucune photo pour le moment",
  "Full name": "Nom complet",
  "Email address": "Adresse courriel",
  Phone: "Téléphone",
  Breed: "Race",
  "New pet name": "Nom du nouvel animal",
  "Handling notes": "Notes de manipulation",
  "Safety warnings": "Avertissements de sécurité",
  "New safety warning": "Nouvel avertissement de sécurité",
  "No structured warnings": "Aucun avertissement structuré",
  "Visit history": "Historique des visites",
  "Complete history": "Historique complet",
  "Book again": "Réserver de nouveau",
  "Add an appointment": "Ajouter un rendez-vous",
  "Choose the visit": "Choisir la visite",
  "Choose a location": "Choisir un emplacement",
  "Checking live openings…": "Vérification des disponibilités…",
  "Live openings found": "Disponibilités trouvées",
  "No openings in these dates.": "Aucune disponibilité à ces dates.",
  "No openings in these dates. Load more or try another service.": "Aucune disponibilité à ces dates. Affichez-en plus ou essayez un autre service.",
  "Conflict-safe booking": "Réservation sans conflit",
  "Front desk booking": "Réservation à la réception",
  "Live capacity, without leaving the workspace. Find the client once, then confirm.": "Capacité en direct sans quitter l’espace. Trouvez le client, puis confirmez.",
  "Client communications": "Communications clients",
  "Every confirmation, reminder, pickup note, and receipt in one traceable queue.": "Chaque confirmation, rappel, avis de collecte et reçu dans une file traçable.",
  Templates: "Modèles",
  "Message queue": "File de messages",
  Compose: "Rédiger",
  "New communication": "Nouvelle communication",
  "Compose client message": "Rédiger un message au client",
  Client: "Client",
  Channel: "Canal",
  Category: "Catégorie",
  "Schedule (optional)": "Planifier (facultatif)",
  Subject: "Objet",
  Message: "Message",
  "Choose a client": "Choisir un client",
  Transactional: "Transactionnel",
  Marketing: "Marketing",
  "Add to delivery queue": "Ajouter à la file d’envoi",
  "Schedule message": "Planifier le message",
  "Delivery history": "Historique d’envoi",
  "No messages in this view.": "Aucun message dans cette vue.",
  "Choose a message to see its delivery history.": "Choisissez un message pour voir son historique d’envoi.",
  "Needs action": "Action requise",
  "All messages": "Tous les messages",
  "Mark sent": "Marquer comme envoyé",
  "Mark delivered": "Marquer comme livré",
  "Mark handled": "Marquer comme traité",
  "Cancel schedule": "Annuler la planification",
  "Automation template": "Modèle d’automatisation",
  Active: "Actif",
  Name: "Nom",
  "Save template": "Enregistrer le modèle",
  "Available fields:": "Champs disponibles :",
  "Services & pricing": "Services et tarifs",
  "Control what clients can book, how long it takes, and the starting price.": "Contrôlez ce que les clients peuvent réserver, la durée et le prix de départ.",
  "Add service": "Ajouter un service",
  "Edit service": "Modifier le service",
  "No active services": "Aucun service actif",
  Duration: "Durée",
  "Duration (minutes)": "Durée (minutes)",
  Price: "Prix",
  Deposit: "Acompte",
  "Available for online booking": "Disponible pour la réservation en ligne",
  Administrator: "Administrateur",
  Employee: "Employé",
  Groomer: "Toiletteur",
  Bather: "Préposé au bain",
  Receptionist: "Réceptionniste",
  Accountant: "Comptable",
  Contractor: "Travailleur autonome",
  "CRM access": "Accès au CRM",
  "Employee portal": "Portail employé",
  "Weekly availability": "Disponibilité hebdomadaire",
  "Compensation rules": "Règles de rémunération",
  "Effective from": "En vigueur à partir du",
  Hourly: "Horaire",
  Commission: "Commission",
  "Apply configured overtime rule": "Appliquer la règle d’heures supplémentaires configurée",
  "Care workflow and timesheets": "Flux de soins et feuilles de temps",
  "Care, messages, and timesheets": "Soins, messages et feuilles de temps",
  "Employee weeks": "Semaines des employés",
  "Choose a teammate.": "Choisissez un membre de l’équipe.",
  "Choose a timesheet to review.": "Choisissez une feuille de temps à vérifier.",
  "No timesheets started this week.": "Aucune feuille de temps commencée cette semaine.",
  Approve: "Approuver",
  Approved: "Approuvée",
  Submitted: "Soumise",
  Draft: "Brouillon",
  Reopen: "Rouvrir",
  "Save changes": "Enregistrer les modifications",
  "Loading workforce records…": "Chargement des dossiers de main-d’œuvre…",
  Stock: "Stock",
  "Purchase orders": "Bons de commande",
  Suppliers: "Fournisseurs",
  "Export CSV": "Exporter en CSV",
  Supplier: "Fournisseur",
  "Stock item": "Article en stock",
  "Add supplier": "Ajouter un fournisseur",
  "Supplier name": "Nom du fournisseur",
  "Contact name": "Nom du contact",
  Website: "Site Web",
  "Account number": "Numéro de compte",
  "Payment terms (days)": "Délai de paiement (jours)",
  Notes: "Notes",
  "Add stock item": "Ajouter un article",
  "Item name": "Nom de l’article",
  Type: "Type",
  "Grooming supply": "Produit de toilettage",
  "Retail product": "Produit de détail",
  "Stock unit": "Unité de stock",
  "Preferred supplier": "Fournisseur privilégié",
  "None yet": "Aucun pour le moment",
  "Opening quantity": "Quantité initiale",
  "Reorder at": "Seuil de commande",
  "Target stock": "Stock cible",
  "Preferred order": "Commande privilégiée",
  "Unit cost": "Coût unitaire",
  "Retail price": "Prix de détail",
  "New purchase order": "Nouveau bon de commande",
  "Expected delivery": "Livraison prévue",
  Item: "Article",
  Quantity: "Quantité",
  Shipping: "Livraison",
  Tax: "Taxe",
  "Order notes": "Notes de commande",
  "Create draft purchase order": "Créer le bon de commande brouillon",
  "On hand": "En stock",
  "At or below reorder point": "Au seuil de commande ou en dessous",
  "Inventory value": "Valeur de l’inventaire",
  "Book value": "Valeur comptable",
  "No stock movement has been recorded yet.": "Aucun mouvement de stock n’a encore été enregistré.",
  "Payments & closeout": "Paiements et clôture",
  "Reconcile every tender, tax dollar, tip, and refund.": "Rapprochez chaque paiement, taxe, pourboire et remboursement.",
  "Closeout date": "Date de clôture",
  "Tax settings": "Paramètres de taxes",
  "Net collected": "Montant net encaissé",
  Payments: "Paiements",
  Refunds: "Remboursements",
  "Tax recorded": "Taxes comptabilisées",
  "Before refunds": "Avant remboursements",
  "Explicit adjustments": "Ajustements explicites",
  "No payments recorded for this day.": "Aucun paiement enregistré pour cette journée.",
  "Count the cash drawer": "Compter la caisse",
  "Expected cash": "Encaisse attendue",
  "Counted cash": "Encaisse comptée",
  "Cash variance": "Écart de caisse",
  "Closeout note": "Note de clôture",
  "Close business day": "Clôturer la journée",
  "Reopen closeout": "Rouvrir la clôture",
  "Closed business day": "Journée clôturée",
  "Balanced snapshot": "Instantané équilibré",
  "Tender reconciliation": "Rapprochement des paiements",
  "Choose payment": "Choisir le paiement",
  "Collect payment, add a tip, or record a refund": "Encaisser, ajouter un pourboire ou enregistrer un remboursement",
  "Checkout & receipt": "Paiement et reçu",
  Subtotal: "Sous-total",
  Discount: "Rabais",
  Tip: "Pourboire",
  Total: "Total",
  "No tip": "Aucun pourboire",
  Cash: "Comptant",
  "Card terminal": "Terminal de paiement",
  "E-transfer": "Virement électronique",
  "Other external": "Autre paiement externe",
  "Record payment": "Enregistrer le paiement",
  "Issue refund": "Effectuer un remboursement",
  "Owner intelligence": "Analytique pour propriétaire",
  "Know what is growing—and what is leaking.": "Voyez ce qui progresse et ce qui fuit.",
  "Average ticket": "Panier moyen",
  "Avg ticket": "Panier moyen",
  "Net sales": "Ventes nettes",
  "Booked hours": "Heures réservées",
  "Client retention": "Fidélisation des clients",
  "Demand recovery": "Récupération de la demande",
  "Location scoreboard": "Comparatif des emplacements",
  "Location settings": "Paramètres de l’emplacement",
  "People with access": "Personnes ayant accès",
  "Manage team access": "Gérer l’accès de l’équipe",
  "Booking rules": "Règles de réservation",
  "Accept online bookings": "Accepter les réservations en ligne",
  "Require online deposit": "Exiger un acompte en ligne",
  "Cancellation window": "Délai d’annulation",
  "Booking window": "Fenêtre de réservation",
  "Cleanup buffer": "Temps de préparation",
  "Loading your salon setup…": "Chargement de la configuration du salon…",
  "Loading payments and plan…": "Chargement des paiements et du forfait…",
  "Care record": "Dossier de soins",
  "Live care record": "Dossier de soins en direct",
  "Coat assessment": "Évaluation du pelage",
  "Not assessed": "Non évalué",
  Healthy: "Sain",
  Tangled: "Emmêlé",
  Matted: "Feutré",
  "Severely matted": "Très feutré",
  "Skin concern": "Problème de peau",
  "Capture the care story": "Documenter les soins",
  "Grooming report card": "Bilan de toilettage",
  "Client price approvals": "Approbations de prix par le client",
  "Internal groomer notes": "Notes internes du toiletteur",
  "Coat issue": "Problème de pelage",
  "High priority": "Priorité élevée",
  Critical: "Critique",
  Standard: "Standard",
  "Requested": "Demandé",
  "Confirmed": "Confirmé",
  "Arrived": "Arrivé",
  "Bathing": "Bain",
  "Drying": "Séchage",
  "Grooming": "Toilettage",
  "Quality Check": "Contrôle qualité",
  "Ready": "Prêt",
  "Completed": "Terminé",
  "Cancelled": "Annulé",
  "No Show": "Absent",
  "Confirm request": "Confirmer la demande",
  "Check in": "Enregistrer l’arrivée",
  "Start bathing": "Commencer le bain",
  "Move to drying": "Passer au séchage",
  "Start grooming": "Commencer le toilettage",
  "Send to quality check": "Passer au contrôle qualité",
  "Mark ready for pickup": "Marquer prêt pour le départ",
  "Complete appointment": "Terminer le rendez-vous",
  Cancel: "Annuler",
  Close: "Fermer",
  Remove: "Supprimer",
  Save: "Enregistrer",
  Saving: "Enregistrement",
  "Saving…": "Enregistrement…",
  "Adding…": "Ajout…",
  "Loading…": "Chargement…",
  "Creating…": "Création…",
  "Recording…": "Enregistrement…",
  "Refreshing…": "Actualisation…",
  Refresh: "Actualiser",
  Search: "Rechercher",
  From: "Du",
  To: "Au",
  Date: "Date",
  Status: "Statut",
  Actions: "Actions",
  Description: "Description",
  Reference: "Référence",
  Email: "Courriel",
  City: "Ville",
  Country: "Pays",
  Address: "Adresse",
  "Postal code": "Code postal",
  Role: "Rôle",
  Permission: "Permission",
  Permissions: "Permissions",
  "Previous week": "Semaine précédente",
  "Next week": "Semaine suivante",
  "Week of": "Semaine du",
  Monday: "Lundi",
  Tuesday: "Mardi",
  Wednesday: "Mercredi",
  Thursday: "Jeudi",
  Friday: "Vendredi",
  Saturday: "Samedi",
  Sunday: "Dimanche",
};

const inlinePhrases: Array<[RegExp, string]> = [
  [/\bappointments?\b/gi, "rendez-vous"],
  [/\bclients?\b/gi, "clients"],
  [/\bpets?\b/gi, "animaux"],
  [/\bservices?\b/gi, "services"],
  [/\bemployees?\b/gi, "employés"],
  [/\bteam members?\b/gi, "membres de l’équipe"],
  [/\btimesheets?\b/gi, "feuilles de temps"],
  [/\bweek\b/gi, "semaine"],
  [/\bpayment\b/gi, "paiement"],
  [/\brefund\b/gi, "remboursement"],
  [/\binventory\b/gi, "inventaire"],
  [/\blocation\b/gi, "emplacement"],
  [/\bloading\b/gi, "chargement"],
  [/\bfailed\b/gi, "échoué"],
  [/\brequired\b/gi, "requis"],
  [/\bpending\b/gi, "en attente"],
  [/\bapproved\b/gi, "approuvé"],
  [/\bsubmitted\b/gi, "soumis"],
  [/\bactive\b/gi, "actif"],
  [/\bavailable\b/gi, "disponible"],
];

function keepCapitalization(source: string, translated: string) {
  if (!source || source[0] !== source[0].toUpperCase()) return translated;
  return translated[0].toUpperCase() + translated.slice(1);
}

export function translateCrmText(value: string): string {
  if (!value.trim()) return value;
  const leading = value.match(/^\s*/)?.[0] || "";
  const trailing = value.match(/\s*$/)?.[0] || "";
  const text = value.slice(leading.length, value.length - trailing.length || undefined);
  const exact = french[text];
  if (exact) return `${leading}${exact}${trailing}`;

  const greeting = text.match(/^Good morning, (.+)\.$/);
  if (greeting) return `${leading}Bonjour, ${greeting[1]}.${trailing}`;
  const onboardingGreeting = text.match(/^Let’s open the doors, (.+)\.$/);
  if (onboardingGreeting) return `${leading}Ouvrons les portes, ${onboardingGreeting[1]}.${trailing}`;
  const countMatch = text.match(/^(\d+) (appointments?|messages?|items?|lines?|events?|weeks?)$/i);
  if (countMatch) {
    const names: Record<string, string> = { appointment: "rendez-vous", appointments: "rendez-vous", message: "message", messages: "messages", item: "article", items: "articles", line: "ligne", lines: "lignes", event: "événement", events: "événements", week: "semaine", weeks: "semaines" };
    return `${leading}${countMatch[1]} ${names[countMatch[2].toLowerCase()]}${trailing}`;
  }

  let translated = text;
  for (const [pattern, replacement] of inlinePhrases) {
    translated = translated.replace(pattern, (matched) => keepCapitalization(matched, replacement));
  }
  return `${leading}${translated}${trailing}`;
}
