import { and, asc, eq, gte, inArray, lt } from "drizzle-orm";
import { appointments, expenses, inventoryMovements, locations, paymentEvents, payrollLines, payrollPeriods, services, staff, staffAvailability } from "../../../db/schema";
import { requireBookkeepingAccess, requireSalonAccess, requireWorkspacePermission, salonApiError, SalonAccessError } from "../../salon-access";
import { dateKeyInZone, weekdayForDateKey, zonedDayBounds } from "../../../lib/time-zone";
import { expenseBookValues } from "../../../lib/accounting";
import { AnalyticsAppointment, AnalyticsPayment, buildInsights, change, signedNetSale, summarizeOperations } from "../../../lib/owner-analytics";

const datePattern = /^\d{4}-\d{2}-\d{2}$/;
function validDate(value: string) { const parsed = new Date(`${value}T12:00:00.000Z`); return datePattern.test(value) && !Number.isNaN(parsed.getTime()) && parsed.toISOString().slice(0, 10) === value; }
function plusDays(day: string, amount: number) { const date = new Date(`${day}T12:00:00.000Z`); date.setUTCDate(date.getUTCDate() + amount); return date.toISOString().slice(0, 10); }
function rangeDays(from: string, to: string) { return Math.floor((Date.parse(`${to}T12:00:00Z`) - Date.parse(`${from}T12:00:00Z`)) / 86_400_000) + 1; }
function dateKeys(from: string, to: string) { const result: string[] = []; for (let day = from; day <= to; day = plusDays(day, 1)) result.push(day); return result; }
function minutes(time: string) { const [hour, minute] = time.split(":").map(Number); return hour * 60 + minute; }

export async function GET(request: Request) {
  try {
    const { db, membership } = await requireSalonAccess(); requireWorkspacePermission(membership, "reports"); requireBookkeepingAccess(membership);
    const permittedIds = membership.locations.map((item) => item.locationId); if (!permittedIds.includes(membership.locationId)) throw new SalonAccessError("Location access unavailable.", 403);
    const locationRows = await db.select({ id: locations.id, name: locations.name, currency: locations.currency, timezone: locations.timezone }).from(locations).where(and(eq(locations.organizationId, membership.organizationId), inArray(locations.id, permittedIds), eq(locations.active, true))).orderBy(asc(locations.name));
    const selected = locationRows.find((item) => item.id === membership.locationId); if (!selected) throw new SalonAccessError("Location not found.", 404);
    const params = new URL(request.url).searchParams, today = dateKeyInZone(new Date(), selected.timezone), to = params.get("to") || today, from = params.get("from") || plusDays(to, -29);
    if (!validDate(from) || !validDate(to) || from > to || rangeDays(from, to) > 366 || to > today) throw new SalonAccessError("Choose a completed reporting range of up to 366 days.", 400);
    const days = rangeDays(from, to), previousTo = plusDays(from, -1), previousFrom = plusDays(previousTo, -days + 1), broadStart = zonedDayBounds(previousFrom, selected.timezone).start.toISOString(), broadEnd = zonedDayBounds(to, selected.timezone).end.toISOString();
    const [appointmentRows, paymentRows, expenseRows, inventoryRows, periodRows, lineRows, availabilityRows] = await Promise.all([
      db.select({ id: appointments.id, locationId: appointments.locationId, clientId: appointments.clientId, petId: appointments.petId, serviceId: appointments.serviceId, serviceName: services.name, staffId: appointments.staffId, staffName: staff.displayName, status: appointments.status, startsAt: appointments.startsAt, endsAt: appointments.endsAt }).from(appointments).innerJoin(services, eq(appointments.serviceId, services.id)).leftJoin(staff, eq(appointments.staffId, staff.id)).where(and(eq(appointments.organizationId, membership.organizationId), inArray(appointments.locationId, permittedIds))).orderBy(asc(appointments.startsAt)),
      db.select({ locationId: paymentEvents.locationId, appointmentId: paymentEvents.appointmentId, kind: paymentEvents.kind, amountCents: paymentEvents.amountCents, taxAmountCents: paymentEvents.taxAmountCents, tipAmountCents: paymentEvents.tipAmountCents, occurredAt: paymentEvents.occurredAt }).from(paymentEvents).where(and(eq(paymentEvents.organizationId, membership.organizationId), inArray(paymentEvents.locationId, permittedIds), eq(paymentEvents.status, "succeeded"), gte(paymentEvents.occurredAt, broadStart), lt(paymentEvents.occurredAt, broadEnd))),
      db.select().from(expenses).where(and(eq(expenses.organizationId, membership.organizationId), inArray(expenses.locationId, permittedIds), eq(expenses.status, "posted"), gte(expenses.paidOn, previousFrom), lt(expenses.paidOn, plusDays(to, 1)))),
      db.select().from(inventoryMovements).where(and(eq(inventoryMovements.organizationId, membership.organizationId), inArray(inventoryMovements.locationId, permittedIds), gte(inventoryMovements.occurredAt, broadStart), lt(inventoryMovements.occurredAt, broadEnd))),
      db.select().from(payrollPeriods).where(and(eq(payrollPeriods.organizationId, membership.organizationId), inArray(payrollPeriods.locationId, permittedIds))),
      db.select().from(payrollLines).where(and(eq(payrollLines.organizationId, membership.organizationId), inArray(payrollLines.locationId, permittedIds))),
      db.select().from(staffAvailability).where(and(eq(staffAvailability.organizationId, membership.organizationId), inArray(staffAvailability.locationId, permittedIds), eq(staffAvailability.active, true))),
    ]);
    const periodById = new Map(periodRows.map((item) => [item.id, item]));
    type LocationRow = typeof locationRows[number];
    function bounds(dayFrom: string, dayTo: string, location: LocationRow) { return { start: zonedDayBounds(dayFrom, location.timezone).start.toISOString(), end: zonedDayBounds(dayTo, location.timezone).end.toISOString() }; }
    function summarize(location: LocationRow, dayFrom: string, dayTo: string) {
      const window = bounds(dayFrom, dayTo, location); const scopedAll = appointmentRows.filter((item) => item.locationId === location.id) as AnalyticsAppointment[]; const scopedAppointments = scopedAll.filter((item) => item.startsAt >= window.start && item.startsAt < window.end); const scopedPayments = paymentRows.filter((item) => item.locationId === location.id && item.occurredAt >= window.start && item.occurredAt < window.end) as AnalyticsPayment[];
      const capacity = new Map<string, number>(); for (const day of dateKeys(dayFrom, dayTo)) for (const row of availabilityRows.filter((item) => item.locationId === location.id && item.weekday === weekdayForDateKey(day))) capacity.set(row.staffId, (capacity.get(row.staffId) || 0) + Math.max(0, minutes(row.endTime) - minutes(row.startTime)));
      const grossPayrollCents = lineRows.filter((line) => { const period = periodById.get(line.payrollPeriodId); return period?.locationId === location.id && ["approved", "exported"].includes(period.status) && period.endsOn >= dayFrom && period.endsOn <= dayTo; }).reduce((sum, line) => sum + line.grossPayCents, 0);
      const operatingExpenseCents = expenseRows.filter((item) => item.locationId === location.id && item.paidOn >= dayFrom && item.paidOn <= dayTo && !["payroll", "grooming_supplies", "retail_inventory"].includes(item.category)).reduce((sum, item) => sum + expenseBookValues(item).operatingExpenseCents, 0);
      const inventoryCostCents = inventoryRows.filter((item) => item.locationId === location.id && item.occurredAt >= window.start && item.occurredAt < window.end && ["usage", "retail_sale", "waste"].includes(item.kind)).reduce((sum, item) => sum + item.totalCostCents, 0);
      return { metrics: summarizeOperations({ appointments: scopedAppointments, allAppointments: scopedAll, payments: scopedPayments, availableMinutesByStaff: capacity, grossPayrollCents, operatingExpenseCents, inventoryCostCents }), appointments: scopedAppointments, allAppointments: scopedAll, payments: scopedPayments, capacity };
    }
    const current = summarize(selected, from, to), previous = summarize(selected, previousFrom, previousTo); const appointmentMap = new Map(current.allAppointments.map((item) => [item.id, item]));
    const daily = dateKeys(from, to).map((day) => { const dayBounds = zonedDayBounds(day, selected.timezone); const rows = current.payments.filter((item) => item.occurredAt >= dayBounds.start.toISOString() && item.occurredAt < dayBounds.end.toISOString()); return { key: day, label: new Intl.DateTimeFormat("en-CA", { month: "short", day: "numeric", timeZone: selected.timezone }).format(dayBounds.start), netSalesCents: rows.reduce((sum, item) => sum + signedNetSale(item), 0), appointments: current.appointments.filter((item) => item.startsAt >= dayBounds.start.toISOString() && item.startsAt < dayBounds.end.toISOString()).length }; });
    const group = (kind: "staff" | "service") => { const map = new Map<string, { key: string; label: string; netSalesCents: number; appointments: number; completed: number; bookedMinutes: number }>(); for (const appointment of current.appointments) { const key = kind === "staff" ? appointment.staffId || "unassigned" : appointment.serviceId, label = kind === "staff" ? appointment.staffName || "Unassigned" : appointment.serviceName; const item = map.get(key) || { key, label, netSalesCents: 0, appointments: 0, completed: 0, bookedMinutes: 0 }; item.appointments += 1; if (appointment.status === "completed") item.completed += 1; if (!["cancelled", "no_show"].includes(appointment.status)) item.bookedMinutes += Math.max(0, Math.round((Date.parse(appointment.endsAt) - Date.parse(appointment.startsAt)) / 60000)); map.set(key, item); } for (const payment of current.payments) { const appointment = appointmentMap.get(payment.appointmentId); if (!appointment) continue; const key = kind === "staff" ? appointment.staffId || "unassigned" : appointment.serviceId; const item = map.get(key); if (item) item.netSalesCents += signedNetSale(payment); } return [...map.values()].map((item) => ({ ...item, averageTicketCents: item.completed ? Math.round(item.netSalesCents / item.completed) : 0, revenuePerBookedHourCents: item.bookedMinutes ? Math.round(item.netSalesCents * 60 / item.bookedMinutes) : 0, utilizationBps: kind === "staff" ? Math.round(item.bookedMinutes * 10000 / Math.max(1, current.capacity.get(item.key) || 0)) : 0 })).sort((a, b) => b.netSalesCents - a.netSalesCents); };
    const comparisons = Object.fromEntries(["netSalesCents", "appointments", "averageTicketCents", "utilizationBps", "retentionBps", "rebookingBps", "laborBps", "contributionCents"].map((key) => [key, change(current.metrics[key as keyof typeof current.metrics] as number, previous.metrics[key as keyof typeof previous.metrics] as number)]));
    const locationComparison = locationRows.map((location) => { const result = summarize(location, from, to).metrics; return { id: location.id, name: location.name, currency: location.currency, netSalesCents: result.netSalesCents, appointments: result.appointments, utilizationBps: result.utilizationBps, laborBps: result.laborBps, contributionCents: result.contributionCents }; }).sort((a, b) => b.netSalesCents - a.netSalesCents);
    return Response.json({ range: { from, to, previousFrom, previousTo, days }, location: selected, metrics: current.metrics, previous: previous.metrics, comparisons, daily, staffPerformance: group("staff"), servicePerformance: group("service"), locationComparison, insights: buildInsights(current.metrics, previous.metrics), disclaimer: "Management analytics from recorded payments, approved payroll, posted overhead, inventory movements, appointments, and published availability. Contribution excludes employer payroll burden, income tax, depreciation, debt service, and unrecorded costs.", exportUrl: `/api/reports/export?from=${from}&to=${to}` });
  } catch (error) { return salonApiError(error, "Owner intelligence unavailable"); }
}
