import Link from "next/link";
import { and, eq } from "drizzle-orm";
import { getDb } from "../../../../db";
import { releaseExpiredBookingHolds } from "../../../../db/booking-holds";
import { appointments, locations, onlinePaymentSessions, organizations, pets, services } from "../../../../db/schema";

export const dynamic = "force-dynamic";
export const metadata = { title: "Booking deposit · Coat & Care", robots: { index: false, follow: false } };

export default async function BookingPaymentPage({ params, searchParams }: { params: Promise<{ id: string }>; searchParams: Promise<{ result?: string }> }) {
  const { id } = await params; const { result } = await searchParams; const db = getDb();
  let [row] = await db.select({ payment: onlinePaymentSessions, appointment: appointments, petId: pets.id, petName: pets.name, serviceId: services.id, serviceName: services.name, organizationName: organizations.name, organizationSlug: organizations.slug, locationName: locations.name, locationSlug: locations.slug, city: locations.city, region: locations.region, timezone: locations.timezone }).from(onlinePaymentSessions)
    .innerJoin(appointments, eq(onlinePaymentSessions.appointmentId, appointments.id)).innerJoin(pets, eq(appointments.petId, pets.id)).innerJoin(services, eq(appointments.serviceId, services.id)).innerJoin(organizations, eq(appointments.organizationId, organizations.id)).innerJoin(locations, eq(appointments.locationId, locations.id))
    .where(and(eq(onlinePaymentSessions.id, id), eq(onlinePaymentSessions.purpose, "deposit"))).limit(1);
  if (row?.payment.status === "open" && new Date(row.payment.expiresAt) <= new Date()) { await releaseExpiredBookingHolds(db, row.appointment.locationId); [row] = await db.select({ payment: onlinePaymentSessions, appointment: appointments, petId: pets.id, petName: pets.name, serviceId: services.id, serviceName: services.name, organizationName: organizations.name, organizationSlug: organizations.slug, locationName: locations.name, locationSlug: locations.slug, city: locations.city, region: locations.region, timezone: locations.timezone }).from(onlinePaymentSessions).innerJoin(appointments, eq(onlinePaymentSessions.appointmentId, appointments.id)).innerJoin(pets, eq(appointments.petId, pets.id)).innerJoin(services, eq(appointments.serviceId, services.id)).innerJoin(organizations, eq(appointments.organizationId, organizations.id)).innerJoin(locations, eq(appointments.locationId, locations.id)).where(eq(onlinePaymentSessions.id, id)).limit(1); }
  if (!row) return <main className="payment-return"><section><span className="payment-return-mark muted">?</span><small>Secure booking deposit</small><h1>This payment link isn’t available.</h1><p>It may have expired or the address may be incomplete. Return to the salon storefront to choose a live opening.</p><Link className="primary-button" href="/">Return to booking</Link></section></main>;
  const now = new Date(); const paid = row.payment.status === "paid" && row.appointment.depositStatus === "paid"; const open = row.payment.status === "open" && new Date(row.payment.expiresAt) > now; const releasing = row.payment.status === "open" && row.appointment.depositStatus === "pending" && !open; const storefront = `/book/${encodeURIComponent(row.organizationSlug)}/${encodeURIComponent(row.locationSlug)}`; const rebook = `${storefront}?${new URLSearchParams({ pet: row.petId, service: row.serviceId }).toString()}`;
  const startsAt = new Intl.DateTimeFormat("en-CA", { timeZone: row.timezone, weekday: "long", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(row.appointment.startsAt)); const money = new Intl.NumberFormat(row.payment.currency === "USD" ? "en-US" : "en-CA", { style: "currency", currency: row.payment.currency }).format(row.payment.amountCents / 100); const expiresAt = new Intl.DateTimeFormat("en-CA", { timeZone: row.timezone, hour: "numeric", minute: "2-digit" }).format(new Date(row.payment.expiresAt));
  const heading = paid ? `${row.petName} is booked.` : open ? result === "cancelled" ? "Your opening is still held." : "We’re confirming your payment." : releasing ? "The payment window closed." : "This hold has expired.";
  const copy = paid ? `The ${money} deposit is recorded. ${row.serviceName} is scheduled for ${startsAt} at ${row.locationName}.` : open ? `Complete the ${money} deposit before ${expiresAt}. Only verified payment confirms the booking.` : releasing ? "We’re allowing a short verification window for any payment completed at the deadline, then the opening returns to live availability." : "No payment was recorded, so the opening returned to live availability.";
  const actions = paid ? <><Link className="primary-button wide" href={rebook}>Book another visit</Link><p className="payment-return-note">Your private pet-parent link and confirmation are on their way.</p></> : open && result === "success" ? <a className="primary-button wide" href={`/booking/payment/${id}?result=checking`}>Refresh payment status</a> : open ? <><a className="primary-button wide" href={row.payment.checkoutUrl}>Complete secure deposit</a><a className="secondary-button wide" href={`/booking/payment/${id}?result=checking`}>Refresh payment status</a></> : releasing ? <a className="secondary-button wide" href={`/booking/payment/${id}?result=checking`}>Refresh status</a> : <Link className="primary-button wide" href={rebook}>Choose another opening for {row.petName}</Link>;
  return <main className="payment-return"><section className={paid ? "paid" : open ? "open" : "expired"}><div className="payment-return-brand"><span>{row.organizationName.slice(0,1)}</span><strong>{row.organizationName}</strong></div><span className="payment-return-mark">{paid ? "✓" : open ? result === "cancelled" ? "↗" : "…" : releasing ? "…" : "×"}</span><small>Secure booking deposit</small><h1>{heading}</h1><p>{copy}</p><div className="payment-visit"><span>♡</span><div><strong>{row.petName} · {row.serviceName}</strong><small>{row.locationName} · {row.city}, {row.region}</small></div></div>{actions}</section></main>;
}
