import { and, eq } from "drizzle-orm";
import { auditEvents, payrollLines, payrollPeriods } from "../../../../db/schema";
import { requirePayrollAccess, requireSalonAccess, salonApiError, SalonAccessError } from "../../../salon-access";

const csv = (value: unknown) => `"${String(value ?? "").replaceAll('"', '""')}"`;
export async function GET(request: Request) {
  try { const { db, membership } = await requireSalonAccess(); requirePayrollAccess(membership); const periodId = new URL(request.url).searchParams.get("periodId") || ""; const [period] = await db.select().from(payrollPeriods).where(and(eq(payrollPeriods.id, periodId), eq(payrollPeriods.organizationId, membership.organizationId), eq(payrollPeriods.locationId, membership.locationId))).limit(1); if (!period) throw new SalonAccessError("Payroll period not found.", 404); const lines = await db.select().from(payrollLines).where(and(eq(payrollLines.payrollPeriodId, period.id), eq(payrollLines.organizationId, membership.organizationId), eq(payrollLines.locationId, membership.locationId))); const rows = [["staff_id","staff_name","period_start","period_end","pay_date","currency","regular_hours","overtime_hours","regular_pay","overtime_pay","service_commission","retail_commission","tips","other_earnings","deductions","reimbursements","gross_pay","payout"], ...lines.map((line) => [line.staffId,line.staffName,period.startsOn,period.endsOn,period.payDate,period.currency,(line.regularMinutes/60).toFixed(2),(line.overtimeMinutes/60).toFixed(2),(line.regularPayCents/100).toFixed(2),(line.overtimePayCents/100).toFixed(2),(line.serviceCommissionCents/100).toFixed(2),(line.retailCommissionCents/100).toFixed(2),(line.tipsCents/100).toFixed(2),(line.otherEarningsCents/100).toFixed(2),(line.deductionsCents/100).toFixed(2),(line.reimbursementsCents/100).toFixed(2),(line.grossPayCents/100).toFixed(2),(line.payoutCents/100).toFixed(2)])]; const now = new Date().toISOString(); if (period.status === "approved") await db.update(payrollPeriods).set({ status: "exported", exportedAt: now, updatedAt: now }).where(eq(payrollPeriods.id, period.id)); await db.insert(auditEvents).values({ id: crypto.randomUUID(), organizationId: membership.organizationId, actorType: "staff", actorId: membership.id, action: "payroll.period_exported", entityType: "payroll_period", entityId: period.id }); return new Response(rows.map((row) => row.map(csv).join(",")).join("\r\n"), { headers: { "content-type": "text/csv; charset=utf-8", "content-disposition": `attachment; filename="payroll-${period.startsOn}-${period.endsOn}.csv"`, "cache-control": "private, no-store" } }); }
  catch (error) { return salonApiError(error, "Payroll export could not be created."); }
}
