"use client";

import { useCallback, useEffect, useMemo, useRef, useState, type CSSProperties } from "react";
import { PERMISSION_LABELS, WORKSPACE_PERMISSIONS, defaultPermissions, type WorkspacePermission } from "../../lib/salon-permissions";

type Service = { id: string; name: string; description: string; durationMinutes: number; bufferMinutes: number; priceFromCents: number; depositCents: number; bathMinutes: number; dryerMinutes: number; groomingTableMinutes: number; kennelMinutes: number; active: boolean };
type TeamMember = { id: string; displayName: string; email?: string | null; role: string; permissions?: WorkspacePermission[] | null };
type Availability = { staffId: string; weekday: number; startTime: string; endTime: string; active: boolean };
type Skill = { staffId: string; serviceId: string };
type ReportPerformance = { key: string; label: string; netSalesCents: number; appointments: number; completed: number; bookedMinutes: number; averageTicketCents: number; revenuePerBookedHourCents: number; utilizationBps: number };
type OwnerMetrics = { netSalesCents: number; tipsCents: number; refundsCents: number; settledTickets: number; appointments: number; completed: number; cancelled: number; noShows: number; exceptionRateBps: number; completionRateBps: number; averageTicketCents: number; bookedMinutes: number; availableMinutes: number; utilizationBps: number; activeClients: number; retainedClients: number; newClients: number; retentionBps: number; rebookingBps: number; grossPayrollCents: number; laborBps: number; operatingExpenseCents: number; inventoryCostCents: number; contributionCents: number; contributionMarginBps: number };
type ReportData = { range: { from: string; to: string; previousFrom: string; previousTo: string; days: number }; location: { name: string; currency: string }; metrics: OwnerMetrics; previous: OwnerMetrics; comparisons: Record<string, number | null>; daily: Array<{ key: string; label: string; netSalesCents: number; appointments: number }>; staffPerformance: ReportPerformance[]; servicePerformance: ReportPerformance[]; locationComparison: Array<{ id: string; name: string; currency: string; netSalesCents: number; appointments: number; utilizationBps: number; laborBps: number; contributionCents: number }>; insights: Array<{ tone: string; title: string; detail: string }>; disclaimer: string; exportUrl: string };

const blankService = { name: "", description: "", durationMinutes: 90, bufferMinutes: 15, priceFromCents: 6500, depositCents: 2000, bathMinutes: 30, dryerMinutes: 30, groomingTableMinutes: 30, kennelMinutes: 0, active: true };
const weekdays = ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"];

function money(cents: number, currency = "CAD") {
  return new Intl.NumberFormat(currency === "USD" ? "en-US" : "en-CA", { style: "currency", currency, maximumFractionDigits: 0 }).format(cents / 100);
}

async function json<T>(response: Response) {
  const result = await response.json() as T & { error?: string };
  if (!response.ok) throw new Error(result.error || "Something went wrong.");
  return result;
}

function useDialogFocus(onClose: () => void, active: boolean, busy = false) {
  const dialog = useRef<HTMLElement>(null);
  const close = useRef(onClose);
  const blocked = useRef(busy);
  useEffect(() => { close.current = onClose; blocked.current = busy; }, [busy, onClose]);
  useEffect(() => {
    if (!active) return;
    const element = dialog.current;
    if (!element) return;
    const previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const focusable = () => Array.from(element.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]'));
    focusable()[0]?.focus();
    const keydown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !blocked.current) { event.preventDefault(); close.current(); return; }
      if (event.key !== "Tab") return;
      const items = focusable();
      if (!items.length) return;
      const first = items[0], last = items[items.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener("keydown", keydown);
    return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = previousOverflow; previousFocus?.focus(); };
  }, [active]);
  return dialog;
}

export function ServicesView({ notify, currency = "CAD" }: { notify: (message: string) => void; currency?: string }) {
  const [services, setServices] = useState<Service[]>([]);
  const [canManage, setCanManage] = useState(false);
  const [editing, setEditing] = useState<(typeof blankService & { id?: string }) | null>(null);
  const [loading, setLoading] = useState(true);
  const [busy, setBusy] = useState(false);
  const [error, setError] = useState("");
  const editorDialog = useDialogFocus(() => setEditing(null), Boolean(editing), busy);
  const load = useCallback(() => fetch("/api/services").then((response) => json<{ services: Service[]; canManage: boolean }>(response)).then((result) => { setServices(result.services); setCanManage(result.canManage); }).catch((reason) => setError(reason.message)).finally(() => setLoading(false)), []);
  useEffect(() => { void load(); }, [load]);

  async function save() {
    if (!editing) return;
    setBusy(true); setError("");
    try {
      const response = await fetch("/api/services", { method: editing.id ? "PATCH" : "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ ...editing, serviceId: editing.id }) });
      await json<{ service: Service }>(response);
      await load(); setEditing(null); notify(editing.id ? "Service updated" : "Service added to your menu");
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save service."); }
    finally { setBusy(false); }
  }

  return <section className="business-panel">
    <div className="business-toolbar"><div><h2>Your service menu</h2><p>Control what clients can book, how long it takes, and the starting price.</p></div>{canManage && <button className="primary-button" onClick={() => setEditing({ ...blankService })}>＋ Add service</button>}</div>
    {error && <p className="inline-error" role="alert">{error}</p>}
    {loading ? <div className="dashboard-loading" role="status" aria-label="Loading service menu"><span /><span /><span /></div> : <div className="service-admin-grid">{services.map((service) => <article className={!service.active ? "inactive" : ""} key={service.id}>
      <header><span className="service-icon">✦</span><span className={service.active ? "availability-pill open" : "availability-pill"}>{service.active ? "Bookable" : "Hidden"}</span></header>
      <h3>{service.name}</h3><p>{service.description}</p>
      <div className="service-admin-meta"><span><small>From</small><strong>{money(service.priceFromCents, currency)}</strong></span><span><small>Time</small><strong>{service.durationMinutes} min</strong></span><span><small>Deposit</small><strong>{money(service.depositCents, currency)}</strong></span></div>
      {canManage && <button className="secondary-button wide" onClick={() => setEditing({ ...service })}>Edit service</button>}
    </article>)}</div>}
    {editing && <div className="modal-backdrop" onMouseDown={(event) => { if (!busy && event.currentTarget === event.target) setEditing(null); }}><section ref={editorDialog} className="business-modal" role="dialog" aria-modal="true" aria-label="Service editor"><header><div><span className="eyebrow">Service settings</span><h2>{editing.id ? "Edit service" : "Create a service"}</h2></div><button disabled={busy} onClick={() => setEditing(null)} aria-label="Close service editor">×</button></header>
      <label>Service name<input value={editing.name} onChange={(event) => setEditing({ ...editing, name: event.target.value })} /></label>
      <label>Description<textarea value={editing.description} onChange={(event) => setEditing({ ...editing, description: event.target.value })} /></label>
      <div className="field-pair"><label>Duration (minutes)<input type="number" min="15" step="15" value={editing.durationMinutes} onChange={(event) => setEditing({ ...editing, durationMinutes: Number(event.target.value) })} /></label><label>Cleanup buffer<input type="number" min="0" step="5" value={editing.bufferMinutes} onChange={(event) => setEditing({ ...editing, bufferMinutes: Number(event.target.value) })} /></label></div>
      <div className="field-pair"><label>Starting price ({currency})<input type="number" min="0" step="1" value={editing.priceFromCents / 100} onChange={(event) => setEditing({ ...editing, priceFromCents: Math.round(Number(event.target.value) * 100) })} /></label><label>Deposit ({currency})<input type="number" min="0" step="1" value={editing.depositCents / 100} onChange={(event) => setEditing({ ...editing, depositCents: Math.round(Number(event.target.value) * 100) })} /></label></div>
      <h3>Capacity phases</h3><p className="modal-help">These minutes reserve the right equipment in sequence so the calendar never promises more than the floor can safely handle.</p>
      <div className="resource-field-grid"><label>Bath station<input type="number" min="0" step="5" value={editing.bathMinutes} onChange={(event) => setEditing({ ...editing, bathMinutes: Number(event.target.value) })} /></label><label>Dryer<input type="number" min="0" step="5" value={editing.dryerMinutes} onChange={(event) => setEditing({ ...editing, dryerMinutes: Number(event.target.value) })} /></label><label>Grooming table<input type="number" min="0" step="5" value={editing.groomingTableMinutes} onChange={(event) => setEditing({ ...editing, groomingTableMinutes: Number(event.target.value) })} /></label><label>Kennel<input type="number" min="0" step="5" value={editing.kennelMinutes} onChange={(event) => setEditing({ ...editing, kennelMinutes: Number(event.target.value) })} /></label></div>
      <label className="toggle-row"><input type="checkbox" checked={editing.active} onChange={(event) => setEditing({ ...editing, active: event.target.checked })} /><span><strong>Available for online booking</strong><small>Turn off to hide it without losing history.</small></span></label>
      {error && <p className="inline-error">{error}</p>}<button className="primary-button wide" disabled={busy} onClick={save}>{busy ? "Saving…" : "Save service"}</button>
    </section></div>}
  </section>;
}

type TeamRole = "manager" | "receptionist" | "groomer" | "bather" | "accountant";
type NewTeamMember = { displayName: string; email: string; role: TeamRole; permissions: WorkspacePermission[] };
type InvitationDelivery = { state: "sent" | "manual_required" | "failed"; recipient: string | null; reason: "missing_recipient" | "provider_unconfigured" | "provider_rejected" | "delivery_error" | null };
const blankTeamMember: NewTeamMember = { displayName: "", email: "", role: "groomer", permissions: defaultPermissions("groomer") };

export function TeamView({ notify, openCreateSignal = 0, locationName = "Current location" }: { notify: (message: string) => void; openCreateSignal?: number; locationName?: string }) {
  const [people, setPeople] = useState<TeamMember[]>([]); const [availability, setAvailability] = useState<Availability[]>([]); const [skills, setSkills] = useState<Skill[]>([]); const [services, setServices] = useState<Array<{ id: string; name: string; active: boolean }>>([]);
  const [selectedId, setSelectedId] = useState(""); const [canManage, setCanManage] = useState(false); const [canCreateAdmin, setCanCreateAdmin] = useState(false); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  const [creating, setCreating] = useState<NewTeamMember | null>(null); const [invitation, setInvitation] = useState<{ displayName: string; employeeInvitationUrl: string; crmUrl: string | null; delivery: InvitationDelivery } | null>(null);
  const createDialog = useDialogFocus(() => setCreating(null), Boolean(creating), busy);
  const inviteDialog = useDialogFocus(() => setInvitation(null), Boolean(invitation));
  const load = useCallback(() => fetch("/api/team").then((response) => json<{ staff: TeamMember[]; availability: Availability[]; skills: Skill[]; services: Array<{ id: string; name: string; active: boolean }>; canManage: boolean; canCreateAdmin: boolean }>(response)).then((result) => { setPeople(result.staff); setAvailability(result.availability); setSkills(result.skills); setServices(result.services); setCanManage(result.canManage); setCanCreateAdmin(result.canCreateAdmin); setSelectedId((current) => result.staff.some((person) => person.id === current) ? current : result.staff[0]?.id || ""); }).catch((reason) => setError(reason.message)), []);
  useEffect(() => { void load(); }, [load]);
  useEffect(() => { if (openCreateSignal < 1 || !canManage) return; const timer = window.setTimeout(() => { setInvitation(null); setCreating({ ...blankTeamMember, permissions: [...blankTeamMember.permissions] }); }, 0); return () => window.clearTimeout(timer); }, [openCreateSignal, canManage]);
  const selected = people.find((person) => person.id === selectedId);
  const availablePermissions = creating?.role === "manager" ? WORKSPACE_PERMISSIONS : WORKSPACE_PERMISSIONS.filter((permission) => defaultPermissions(creating?.role || "groomer").includes(permission));
  const days = useMemo(() => weekdays.map((_, weekday) => availability.find((item) => item.staffId === selectedId && item.weekday === weekday) || { staffId: selectedId, weekday, startTime: "09:00", endTime: "17:00", active: false }), [availability, selectedId]);
  const selectedSkills = skills.filter((item) => item.staffId === selectedId).map((item) => item.serviceId);
  function updateDay(weekday: number, patch: Partial<Availability>) { const next = days.map((day) => day.weekday === weekday ? { ...day, ...patch } : day); setAvailability((current) => [...current.filter((item) => item.staffId !== selectedId), ...next]); }
  function toggleSkill(serviceId: string) { setSkills((current) => current.some((item) => item.staffId === selectedId && item.serviceId === serviceId) ? current.filter((item) => !(item.staffId === selectedId && item.serviceId === serviceId)) : [...current, { staffId: selectedId, serviceId }]); }
  async function save() { setBusy(true); setError(""); try { await json(await fetch("/api/team", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ staffId: selectedId, availability: days.map(({ weekday, startTime, endTime, active }) => ({ weekday, startTime, endTime, active })), serviceIds: selectedSkills }) })); notify(`${selected?.displayName}'s schedule saved`); } catch (reason) { setError(reason instanceof Error ? reason.message : "Could not save schedule."); } finally { setBusy(false); } }
  function chooseRole(role: TeamRole) { if (!creating) return; setCreating({ ...creating, role, permissions: [...defaultPermissions(role)] }); }
  function togglePermission(permission: WorkspacePermission) { if (!creating) return; setCreating({ ...creating, permissions: creating.permissions.includes(permission) ? creating.permissions.filter((item) => item !== permission) : [...creating.permissions, permission] }); }
  async function createMember() { if (!creating) return; setBusy(true); setError(""); try { const result = await json<{ member: TeamMember; employeeInvitationUrl: string; crmUrl: string | null; delivery: InvitationDelivery }>(await fetch("/api/team", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(creating) })); setInvitation({ displayName: result.member.displayName, employeeInvitationUrl: result.employeeInvitationUrl, crmUrl: result.crmUrl, delivery: result.delivery }); setCreating(null); await load(); setSelectedId(result.member.id); notify(result.delivery.state === "sent" ? `Invitation emailed to ${result.delivery.recipient}` : `${result.member.displayName} was added; share the setup link`); } catch (reason) { setError(reason instanceof Error ? reason.message : "The team member could not be added."); } finally { setBusy(false); } }
  async function copy(value: string, message: string) { await navigator.clipboard.writeText(value); notify(message); }
  return <section className="business-panel"><div className="business-toolbar"><div><h2>Team & availability</h2><p>Set working hours and match every service with qualified hands.</p></div><div className="team-toolbar-actions"><span className="team-count">{people.length} active teammates</span>{canManage && <button className="primary-button" onClick={() => { setInvitation(null); setCreating({ ...blankTeamMember, permissions: [...blankTeamMember.permissions] }); }}>＋ Add</button>}</div></div>
    {error && <p className="inline-error" role="alert">{error}</p>}<div className="team-admin-layout"><div className="team-roster">{people.map((person) => <button className={person.id === selectedId ? "selected" : ""} aria-pressed={person.id === selectedId} key={person.id} onClick={() => setSelectedId(person.id)}><span>{person.displayName.slice(0, 2).toUpperCase()}</span><div><strong>{person.displayName}</strong><small>{person.role}</small></div><em>›</em></button>)}</div>
      {selected ? <div className="team-editor"><header><div className="large-initial">{selected.displayName.slice(0, 2).toUpperCase()}</div><div><h2>{selected.displayName}</h2><p>{selected.role} · {locationName}</p></div></header><h3>Weekly availability</h3><div className="availability-list">{days.map((day) => <div key={day.weekday}><label><input disabled={!canManage} type="checkbox" checked={day.active} onChange={(event) => updateDay(day.weekday, { active: event.target.checked })} /><strong>{weekdays[day.weekday]}</strong></label><input disabled={!canManage || !day.active} aria-label={`${weekdays[day.weekday]} start time`} type="time" value={day.startTime} onChange={(event) => updateDay(day.weekday, { startTime: event.target.value })} /><span>to</span><input disabled={!canManage || !day.active} aria-label={`${weekdays[day.weekday]} end time`} type="time" value={day.endTime} onChange={(event) => updateDay(day.weekday, { endTime: event.target.value })} /></div>)}</div>
      <h3>Qualified services</h3><div className="skill-grid">{services.map((service) => <button disabled={!canManage} aria-pressed={selectedSkills.includes(service.id)} className={selectedSkills.includes(service.id) ? "selected" : ""} key={service.id} onClick={() => toggleSkill(service.id)}><span>{selectedSkills.includes(service.id) ? "✓" : "+"}</span>{service.name}</button>)}</div>{canManage && <button className="primary-button wide" disabled={busy} onClick={save}>{busy ? "Saving…" : "Save team settings"}</button>}</div> : <div className="directory-empty detail">Choose a teammate.</div>}</div>
    {creating && <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target && !busy) setCreating(null); }}><section ref={createDialog} className="business-modal team-access-modal" role="dialog" aria-modal="true" aria-label="Add a team member"><header><div><span className="eyebrow">New access</span><h2>Add a team member</h2></div><button disabled={busy} onClick={() => setCreating(null)} aria-label="Close team member editor">×</button></header>
      <label>Full name<input autoFocus value={creating.displayName} onChange={(event) => setCreating({ ...creating, displayName: event.target.value })} placeholder="e.g. Marie Tremblay" /></label>
      <label>Email address<input type="email" value={creating.email} onChange={(event) => setCreating({ ...creating, email: event.target.value })} placeholder="name@example.ca" /><small>Required for automatic delivery and CRM access. Leave blank only for an employee-portal-only profile.</small></label>
      <h3>Role</h3><div className="account-type-grid"><button type="button" aria-pressed={creating.role === "groomer"} className={creating.role === "groomer" ? "selected" : ""} onClick={() => chooseRole("groomer")}><strong>Groomer</strong><small>Care, messages, and timesheets</small></button><button type="button" aria-pressed={creating.role === "bather"} className={creating.role === "bather" ? "selected" : ""} onClick={() => chooseRole("bather")}><strong>Bather</strong><small>Care workflow and timesheets</small></button><button type="button" aria-pressed={creating.role === "receptionist"} className={creating.role === "receptionist" ? "selected" : ""} onClick={() => chooseRole("receptionist")}><strong>Receptionist</strong><small>Scheduling, clients, and checkout</small></button><button type="button" aria-pressed={creating.role === "accountant"} className={creating.role === "accountant" ? "selected" : ""} onClick={() => chooseRole("accountant")}><strong>Accountant</strong><small>Payroll, checkout, and finance</small></button>{canCreateAdmin && <button type="button" aria-pressed={creating.role === "manager"} className={creating.role === "manager" ? "selected" : ""} onClick={() => chooseRole("manager")}><strong>Administrator</strong><small>Salon and team management</small></button>}</div>
      <h3>CRM access</h3><p className="modal-help">Select only what this person needs to view or change. The server enforces the same access.</p><div className="permission-grid">{availablePermissions.map((permission) => <label key={permission}><input type="checkbox" checked={creating.permissions.includes(permission)} onChange={() => togglePermission(permission)} /><span><strong>{PERMISSION_LABELS[permission].label}</strong><small>{PERMISSION_LABELS[permission].description}</small></span></label>)}</div>
      {error && <p className="inline-error" role="alert">{error}</p>}<button className="primary-button wide" disabled={busy || creating.displayName.trim().length < 2 || (!creating.email.trim() && creating.permissions.length > 0)} onClick={createMember}>{busy ? "Creating…" : creating.email ? "Create and send invitation" : creating.permissions.length ? "Enter email to continue" : "Create and show invitation"}</button>
    </section></div>}
    {invitation && <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target) setInvitation(null); }}><section ref={inviteDialog} className="business-modal invitation-result" role="dialog" aria-modal="true" aria-label="Invitation ready"><header><div><span className="eyebrow">{invitation.delivery.state === "sent" ? "Invitation emailed" : "Invitation ready to share"}</span><h2>{invitation.displayName}</h2></div><button onClick={() => setInvitation(null)} aria-label="Close invitation">×</button></header><p>{invitation.delivery.state === "sent" ? `Resend accepted the invitation for ${invitation.delivery.recipient}. Keep the private link below as a backup.` : invitation.delivery.reason === "missing_recipient" ? "No email was entered. Copy this one-time setup link and share it through a private channel." : invitation.delivery.reason === "provider_unconfigured" ? `Automatic email is not configured${invitation.delivery.recipient ? ` for ${invitation.delivery.recipient}` : ""}. Copy this one-time setup link and share it privately.` : "The email provider did not accept the invitation. The team member was still created; share this one-time setup link privately."} It expires in seven days.</p><div className="invite-link"><input aria-label="Employee invitation link" readOnly value={invitation.employeeInvitationUrl} /><button className="secondary-button" onClick={() => copy(invitation.employeeInvitationUrl, "Employee link copied")}>Copy</button></div>{invitation.crmUrl && <><p>The same email also includes the CRM sign-in address. This backup link requires the invited email at sign-in.</p><div className="invite-link"><input aria-label="CRM sign-in link" readOnly value={invitation.crmUrl} /><button className="secondary-button" onClick={() => copy(invitation.crmUrl!, "CRM link copied")}>Copy</button></div></>}<button className="primary-button wide" onClick={() => setInvitation(null)}>Done</button></section></div>}
  </section>;
}

export function ReportsView() {
  const [today] = useState(() => new Date().toISOString().slice(0, 10)); const [from, setFrom] = useState(() => { const day = new Date(); day.setDate(day.getDate() - 29); return day.toISOString().slice(0, 10); }); const [to, setTo] = useState(today); const [data, setData] = useState<ReportData | null>(null); const [error, setError] = useState("");
  useEffect(() => { let cancelled = false; fetch(`/api/reports?from=${from}&to=${to}`, { cache: "no-store" }).then((response) => json<ReportData>(response)).then((result) => { if (!cancelled) setData(result); }).catch((reason) => { if (!cancelled) setError(reason.message); }); return () => { cancelled = true; }; }, [from, to]);
  const currency = data?.location.currency || "CAD", pct = (bps: number) => `${(bps / 100).toFixed(1)}%`, comparison = (key: string, inverse = false) => { const value = data?.comparisons[key]; if (value === null || value === undefined) return <span className="metric-change neutral">New baseline</span>; const positive = inverse ? value <= 0 : value >= 0; return <span className={`metric-change ${positive ? "positive" : "negative"}`}>{value >= 0 ? "↑" : "↓"} {Math.abs(value / 100).toFixed(1)}%</span>; };
  const maxDaily = Math.max(...(data?.daily.map((item) => Math.max(0, item.netSalesCents)) || [1]), 1);
  function preset(days: number) { const end = new Date(); const start = new Date(end); start.setDate(start.getDate() - days + 1); setData(null); setError(""); setFrom(start.toISOString().slice(0, 10)); setTo(end.toISOString().slice(0, 10)); }
  return <section className="owner-intelligence"><div className="intelligence-toolbar"><div><span className="eyebrow">Owner intelligence</span><h2>Know what is growing—and what is leaking.</h2><p>Collected sales, capacity, clients, labor, and operating contribution in one decision surface.</p></div><div className="intelligence-range"><div><button onClick={() => preset(30)}>30D</button><button onClick={() => preset(90)}>90D</button><button onClick={() => preset(365)}>1Y</button></div><label>From<input type="date" value={from} max={to} onChange={(event) => { setData(null); setError(""); setFrom(event.target.value); }} /></label><label>To<input type="date" value={to} min={from} max={today} onChange={(event) => { setData(null); setError(""); setTo(event.target.value); }} /></label>{data && <a href={data.exportUrl}>Export CSV</a>}</div></div>
    {error && <p className="inline-error" role="alert">{error}</p>}{!data ? <div className="dashboard-loading" role="status" aria-label="Loading owner intelligence"><span /><span /><span /></div> : <><div className="intelligence-metrics"><article><span>Net sales</span><strong>{money(data.metrics.netSalesCents, currency)}</strong>{comparison("netSalesCents")}<small>Payments less refunds, tax, and tips</small></article><article><span>Operating contribution</span><strong>{money(data.metrics.contributionCents, currency)}</strong>{comparison("contributionCents")}<small>{pct(data.metrics.contributionMarginBps)} recorded margin</small></article><article><span>Average ticket</span><strong>{money(data.metrics.averageTicketCents, currency)}</strong>{comparison("averageTicketCents")}<small>{data.metrics.completed} completed visits</small></article><article><span>Team utilization</span><strong>{pct(data.metrics.utilizationBps)}</strong>{comparison("utilizationBps")}<small>{(data.metrics.bookedMinutes / 60).toFixed(0)} of {(data.metrics.availableMinutes / 60).toFixed(0)} published hours</small></article><article><span>Client retention</span><strong>{pct(data.metrics.retentionBps)}</strong>{comparison("retentionBps")}<small>{data.metrics.retainedClients} returning · {data.metrics.newClients} new</small></article><article><span>Rebooking</span><strong>{pct(data.metrics.rebookingBps)}</strong>{comparison("rebookingBps")}<small>Completed visits with a later booking</small></article></div>
    <div className="insight-strip">{data.insights.map((item) => <article className={item.tone} key={item.title}><span>{item.tone === "positive" ? "↗" : item.tone === "attention" ? "!" : "◎"}</span><div><strong>{item.title}</strong><p>{item.detail}</p></div></article>)}</div>
    <div className="intelligence-grid"><section className="intelligence-card sales-trend"><header><div><h3>Collected sales rhythm</h3><p>Net of refunds, sales tax, and staff tips</p></div><span>{data.range.from} – {data.range.to}</span></header><div className="sales-bars">{data.daily.map((item) => <div key={item.key} title={`${item.label}: ${money(item.netSalesCents, currency)}`}><span style={{ height: `${Math.max(3, Math.max(0, item.netSalesCents) / maxDaily * 100)}%` }} /><small>{data.range.days <= 45 || item.key.endsWith("01") ? item.label : ""}</small></div>)}</div></section><section className="intelligence-card contribution-card"><header><div><h3>Recorded contribution</h3><p>A management bridge from net sales</p></div></header><div className="contribution-lines"><div><span>Net sales</span><strong>{money(data.metrics.netSalesCents, currency)}</strong></div><div><span>Approved gross payroll <em>{pct(data.metrics.laborBps)}</em></span><strong>−{money(data.metrics.grossPayrollCents, currency)}</strong></div><div><span>Inventory consumed & sold</span><strong>−{money(data.metrics.inventoryCostCents, currency)}</strong></div><div><span>Posted overhead</span><strong>−{money(data.metrics.operatingExpenseCents, currency)}</strong></div><div className="total"><span>Operating contribution</span><strong>{money(data.metrics.contributionCents, currency)}</strong></div></div></section></div>
    <div className="health-grid"><section className="intelligence-card"><header><div><h3>Client engine</h3><p>Demand quality after the first visit</p></div></header><div className="health-rings"><div style={{ "--score": `${data.metrics.retentionBps / 100}%` } as CSSProperties}><strong>{pct(data.metrics.retentionBps)}</strong><span>Retention</span></div><div style={{ "--score": `${data.metrics.rebookingBps / 100}%` } as CSSProperties}><strong>{pct(data.metrics.rebookingBps)}</strong><span>Rebooking</span></div><div style={{ "--score": `${data.metrics.completionRateBps / 100}%` } as CSSProperties}><strong>{pct(data.metrics.completionRateBps)}</strong><span>Completion</span></div></div><footer><span>{data.metrics.activeClients} active clients</span><span>{data.metrics.cancelled} cancellations</span><span>{data.metrics.noShows} no-shows</span></footer></section><section className="intelligence-card location-benchmarks"><header><div><h3>Location scoreboard</h3><p>Only locations you are allowed to access</p></div></header>{data.locationComparison.map((item, index) => <article key={item.id}><b>{index + 1}</b><div><strong>{item.name}</strong><small>{item.appointments} visits · {pct(item.utilizationBps)} utilized</small></div><span><strong>{money(item.netSalesCents, item.currency)}</strong><small>{pct(item.laborBps)} labor</small></span><em className={item.contributionCents >= 0 ? "positive" : "negative"}>{money(item.contributionCents, item.currency)}</em></article>)}</section></div>
    <section className="performance-table intelligence-card"><header><div><h3>Team economics</h3><p>Collected sales and booked capacity—not a performance review in isolation</p></div></header><div className="performance-head"><span>Team member</span><span>Visits</span><span>Net sales</span><span>Avg ticket</span><span>Revenue / booked hour</span><span>Utilization</span></div>{data.staffPerformance.map((item) => <article key={item.key}><strong>{item.label}</strong><span>{item.completed} / {item.appointments}</span><span>{money(item.netSalesCents, currency)}</span><span>{money(item.averageTicketCents, currency)}</span><span>{money(item.revenuePerBookedHourCents, currency)}</span><span><b style={{ width: `${Math.min(100, item.utilizationBps / 100)}%` }} />{pct(item.utilizationBps)}</span></article>)}</section>
    <section className="performance-table services-economics intelligence-card"><header><div><h3>Service economics</h3><p>Use revenue per booked hour to balance price, time, and demand</p></div></header><div className="performance-head"><span>Service</span><span>Visits</span><span>Net sales</span><span>Avg ticket</span><span>Revenue / booked hour</span><span>Booked hours</span></div>{data.servicePerformance.map((item) => <article key={item.key}><strong>{item.label}</strong><span>{item.completed} / {item.appointments}</span><span>{money(item.netSalesCents, currency)}</span><span>{money(item.averageTicketCents, currency)}</span><span>{money(item.revenuePerBookedHourCents, currency)}</span><span>{(item.bookedMinutes / 60).toFixed(1)}h</span></article>)}</section><p className="intelligence-disclaimer">ⓘ {data.disclaimer}</p></>}
  </section>;
}
