"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import { AccountingView } from "./accounting-view";
import { invoiceBalanceCents } from "../../lib/financial-ledger";

type Invoice = { id: string; appointmentId: string; invoiceNumber: string; status: string; subtotalCents: number; discountCents: number; discountReason: string; taxLabel: string; taxRateBps: number; taxCents: number; tipCents: number; totalCents: number; amountPaidCents: number; amountRefundedCents: number; currency: string; updatedAt: string };
type PaymentEvent = { id: string; invoiceId: string; appointmentId: string; kind: "payment" | "refund"; method: string; amountCents: number; note: string; parentPaymentId: string | null; occurredAt: string; invoiceNumber?: string; petName?: string; clientName?: string };
type CheckoutData = { appointment: { id: string; status: string; priceEstimateCents: number; depositCents: number; currency: string }; serviceName: string; petName: string; clientName: string; clientEmail: string; taxLabel: string; taxRateBps: number; organizationName: string; locationName: string; city: string; invoice: Invoice | null; lines: Array<{ id: string; description: string; quantity: number; totalCents: number }>; events: PaymentEvent[]; preview: { taxCents: number; totalCents: number } };
type Closeout = { id: string; businessDate: string; status: "closed" | "reopened"; netCollectedCents: number; expectedCashCents: number; countedCashCents: number; cashVarianceCents: number; salesTaxCents: number; tipsCents: number; refundsCents: number; transactionCount: number; note: string; closedAt: string; reopenedAt: string | null; drifted: boolean };
type FinanceData = { location: { currency: string; taxLabel: string; taxRateBps: number }; day: string; metrics: { collectedCents: number; paymentsCents: number; refundsCents: number; tipsCents: number; taxCents: number; transactionCount: number; byMethod: Record<string, number> }; events: PaymentEvent[]; invoices: Array<Invoice & { petName: string; clientName: string }>; closeout: Closeout | null; canManage: boolean };

function money(cents: number, currency = "CAD") { return new Intl.NumberFormat("en-CA", { style: "currency", currency }).format(cents / 100); }
function methodLabel(value: string) { return ({ cash: "Cash", card_terminal: "Card terminal", e_transfer: "E-transfer", external: "Other external" } as Record<string, string>)[value] || value; }
function statusLabel(value: string) { return value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase()); }
async function result<T>(response: Response) { const body = await response.json() as T & { error?: string }; if (!response.ok) throw new Error(body.error || "Something went wrong."); return body; }
function dateKeyInZone(value: Date, timeZone: string) {
  return new Intl.DateTimeFormat("en-CA", { timeZone, year: "numeric", month: "2-digit", day: "2-digit" }).format(value);
}
function timeInZone(value: string, timeZone: string) {
  return new Intl.DateTimeFormat("en-CA", { timeZone, hour: "numeric", minute: "2-digit" }).format(new Date(value));
}
function dateTimeInZone(value: string, timeZone: string) {
  return new Intl.DateTimeFormat("en-CA", { timeZone, month: "short", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
}
function useModalDialog(onClose: () => void, active = true, busy = false) {
  const dialogRef = useRef<HTMLElement>(null);
  const closeRef = useRef(onClose);
  const busyRef = useRef(busy);
  useEffect(() => { closeRef.current = onClose; busyRef.current = busy; }, [busy, onClose]);
  useEffect(() => {
    if (!active) return;
    const element = dialogRef.current;
    if (!element) return;
    const previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const previousOverflow = document.body.style.overflow;
    document.body.style.overflow = "hidden";
    const focusable = () => Array.from(element.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]'));
    focusable()[0]?.focus();
    const keydown = (event: KeyboardEvent) => {
      if (event.key === "Escape" && !busyRef.current) { event.preventDefault(); closeRef.current(); return; }
      if (event.key !== "Tab") return;
      const items = focusable();
      if (!items.length) return;
      const first = items[0], last = items[items.length - 1];
      if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); }
      else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); }
    };
    document.addEventListener("keydown", keydown);
    return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = previousOverflow; previousFocus?.focus(); };
  }, [active]);
  return dialogRef;
}

export function CheckoutModal({ appointmentId, onClose, onRecorded }: { appointmentId: string; onClose: () => void; onRecorded: () => void }) {
  const [data, setData] = useState<CheckoutData | null>(null); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  const [tipCents, setTipCents] = useState(0); const [discountCents, setDiscountCents] = useState(0); const [discountReason, setDiscountReason] = useState(""); const [method, setMethod] = useState("card_terminal"); const [externalReference, setExternalReference] = useState("");
  const [refundPaymentId, setRefundPaymentId] = useState(""); const [refundCents, setRefundCents] = useState(0); const [refundReason, setRefundReason] = useState("");
  useEffect(() => { fetch(`/api/checkout?appointmentId=${encodeURIComponent(appointmentId)}`).then((response) => result<CheckoutData>(response)).then((checkout) => { setData(checkout); setTipCents(checkout.invoice?.tipCents || 0); setDiscountCents(checkout.invoice?.discountCents || 0); setDiscountReason(checkout.invoice?.discountReason || ""); }).catch((reason) => setError(reason instanceof Error ? reason.message : "Checkout unavailable.")); }, [appointmentId]);
  const subtotal = data?.invoice?.subtotalCents ?? data?.appointment.priceEstimateCents ?? 0;
  const taxRate = data?.invoice?.taxRateBps ?? data?.taxRateBps ?? 0;
  const taxCents = Math.round(Math.max(0, subtotal - discountCents) * taxRate / 10_000);
  const totalCents = Math.max(0, subtotal - discountCents) + taxCents + tipCents;
  const balanceCents = invoiceBalanceCents(totalCents, data?.invoice?.amountPaidCents || 0, data?.invoice?.amountRefundedCents || 0);
  const refundablePayments = useMemo(() => (data?.events || []).filter((event) => event.kind === "payment").map((payment) => ({ ...payment, remaining: payment.amountCents - (data?.events || []).filter((event) => event.kind === "refund" && event.parentPaymentId === payment.id).reduce((sum, event) => sum + event.amountCents, 0) })).filter((payment) => payment.remaining > 0), [data]);
  const displayMoney = (cents: number) => money(cents, data?.appointment.currency || "CAD");
  const dialogRef = useModalDialog(onClose, true, busy);

  async function recordPayment() { if (!data || balanceCents < 1) return; setBusy(true); setError(""); try { const checkout = await result<CheckoutData>(await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "record_payment", appointmentId, idempotencyKey: crypto.randomUUID(), method, amountCents: balanceCents, tipCents, discountCents, discountReason, externalReference }) })); setData(checkout); onRecorded(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Payment could not be recorded."); } finally { setBusy(false); } }
  async function onlinePayment(purpose: "deposit" | "invoice") { if (!data || balanceCents < 1) return; setBusy(true); setError(""); try { const checkout = await result<{ url: string }>(await fetch("/api/payments/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ appointmentId, purpose, idempotencyKey: crypto.randomUUID(), tipCents, discountCents, discountReason }) })); window.open(checkout.url, "_blank", "noopener,noreferrer"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Online checkout could not be created."); } finally { setBusy(false); } }
  async function refund() { if (!refundPaymentId || refundCents < 1) return; setBusy(true); setError(""); try { const checkout = await result<CheckoutData>(await fetch("/api/checkout", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ action: "refund", appointmentId, paymentId: refundPaymentId, amountCents: refundCents, reason: refundReason, idempotencyKey: crypto.randomUUID() }) })); setData(checkout); setRefundPaymentId(""); setRefundCents(0); setRefundReason(""); onRecorded(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Refund could not be recorded."); } finally { setBusy(false); } }

  return <div className="modal-backdrop checkout-backdrop" onMouseDown={(event) => { if (!busy && event.currentTarget === event.target) onClose(); }}><section ref={dialogRef} className="checkout-modal" role="dialog" aria-modal="true" aria-label="Appointment checkout">
    <header className="checkout-head"><div><span className="eyebrow">Checkout & receipt</span><h2>{data?.petName || "Loading checkout…"}</h2><p>{data ? `${data.clientName} · ${data.serviceName}` : "Preparing the invoice"}</p></div><div>{data?.invoice && <button className="print-button" onClick={() => window.print()}>Print receipt</button>}<button className="close-round" disabled={busy} onClick={onClose} aria-label="Close checkout">×</button></div></header>
    {error && <p className="inline-error" role="alert">{error}</p>}{!data ? <div className="dashboard-loading" role="status" aria-label="Loading checkout"><span /><span /><span /></div> : <div className="checkout-layout"><div className="checkout-controls">
      <section><h3>Service</h3><div className="checkout-line"><span>{data.serviceName}</span><strong>{displayMoney(subtotal)}</strong></div></section>
      {!data.invoice?.amountPaidCents && <><section><h3>Discount</h3><label className="money-input"><span>{data.appointment.currency}</span><input aria-label={`Discount in ${data.appointment.currency}`} type="number" min="0" step="1" value={discountCents / 100} onChange={(event) => setDiscountCents(Math.max(0, Math.round(Number(event.target.value) * 100)))} /></label>{discountCents > 0 && <input aria-label="Discount reason" className="reason-input" value={discountReason} onChange={(event) => setDiscountReason(event.target.value)} placeholder="Manager reason required" />}</section>
      <section><h3>Tip</h3><div className="tip-options">{[0, 15, 20, 25].map((percent) => { const amount = percent ? Math.round((subtotal - discountCents) * percent / 100) : 0; return <button type="button" aria-pressed={tipCents === amount} className={tipCents === amount ? "selected" : ""} key={percent} onClick={() => setTipCents(amount)}>{percent ? `${percent}%` : "No tip"}<small>{displayMoney(amount)}</small></button>; })}</div></section></>}
      {balanceCents > 0 && <section><h3>In-salon payment</h3><div className="tender-options">{["card_terminal", "cash", "e_transfer", "external"].map((value) => <button type="button" aria-pressed={method === value} className={method === value ? "selected" : ""} key={value} onClick={() => setMethod(value)}>{methodLabel(value)}</button>)}</div>{method !== "cash" && <input aria-label="Terminal or transfer reference" className="reason-input" value={externalReference} onChange={(event) => setExternalReference(event.target.value)} placeholder="Optional terminal or transfer reference" />}</section>}
      {balanceCents > 0 && <section className="online-checkout-section"><h3>Secure online payment</h3><p>Open a Stripe-hosted page for the client. Card details never enter this app.</p><button className="secondary-button wide" disabled={busy} onClick={() => onlinePayment("invoice")}>Collect full balance online</button>{data.appointment.depositCents > 0 && data.appointment.depositCents < balanceCents && <button className="text-button wide" disabled={busy} onClick={() => onlinePayment("deposit")}>Collect {displayMoney(data.appointment.depositCents)} deposit online</button>}</section>}
      {refundablePayments.length > 0 && <section className="refund-section"><h3>Refund a recorded payment</h3><select aria-label="Payment to refund" value={refundPaymentId} onChange={(event) => { const payment = refundablePayments.find((item) => item.id === event.target.value); setRefundPaymentId(event.target.value); setRefundCents(payment?.remaining || 0); }}><option value="">Choose payment</option>{refundablePayments.map((payment) => <option value={payment.id} key={payment.id}>{methodLabel(payment.method)} · {displayMoney(payment.remaining)} refundable</option>)}</select>{refundPaymentId && <><label className="money-input"><span>{data.appointment.currency}</span><input aria-label={`Refund amount in ${data.appointment.currency}`} type="number" min="0.01" step="0.01" value={refundCents / 100} onChange={(event) => setRefundCents(Math.max(0, Math.round(Number(event.target.value) * 100)))} /></label><input aria-label="Refund reason" className="reason-input" value={refundReason} onChange={(event) => setRefundReason(event.target.value)} placeholder="Refund reason required" /><button className="danger-button wide" disabled={busy || !refundReason} onClick={refund}>Record refund</button></>}</section>}
    </div><aside className="receipt-card"><div className="receipt-brand"><span>{data.organizationName.split(/\s+/).map((word) => word[0]).join("").slice(0, 2).toUpperCase()}</span><div><strong>{data.organizationName}</strong><small>{data.locationName} · {data.city}</small></div></div>{data.invoice && <div className="receipt-number"><span>Receipt</span><strong>{data.invoice.invoiceNumber}</strong></div>}<div className="receipt-customer"><strong>{data.clientName}</strong><span>{data.clientEmail}</span></div><div className="receipt-totals"><div><span>Subtotal</span><strong>{displayMoney(subtotal)}</strong></div>{discountCents > 0 && <div><span>Discount</span><strong>−{displayMoney(discountCents)}</strong></div>}<div><span>{data.invoice?.taxLabel || data.taxLabel} ({(taxRate / 100).toFixed(2)}%)</span><strong>{displayMoney(taxCents)}</strong></div>{tipCents > 0 && <div><span>Tip</span><strong>{displayMoney(tipCents)}</strong></div>}<div className="receipt-total"><span>Total</span><strong>{displayMoney(totalCents)}</strong></div>{data.invoice && <><div><span>Payments</span><strong>−{displayMoney(data.invoice.amountPaidCents)}</strong></div>{data.invoice.amountRefundedCents > 0 && <div><span>Refunded</span><strong>+{displayMoney(data.invoice.amountRefundedCents)}</strong></div>}</>}<div className="receipt-balance"><span>Balance due</span><strong>{displayMoney(balanceCents)}</strong></div></div>{data.invoice && <span className={`invoice-status ${data.invoice.status}`}>{statusLabel(data.invoice.status)}</span>}{balanceCents > 0 ? <button className="primary-button wide collect-button" disabled={busy} onClick={recordPayment}>{busy ? "Recording…" : data.appointment.status === "ready" ? `Pay ${displayMoney(balanceCents)} & complete visit` : `Record ${displayMoney(balanceCents)} payment`}</button> : <div className="paid-confirmation"><span>✓</span><strong>Invoice paid</strong><small>{data.appointment.status === "completed" ? "Visit completed · ready to print or share" : "Ready to print or share"}</small></div>}<p className="processor-note">Card details are handled by your terminal—not stored in this app.</p></aside></div>}
  </section></div>;
}

function CloseoutView({ onCheckout, timezone }: { onCheckout: (appointmentId: string) => void; timezone: string }) {
  const [day, setDay] = useState(() => dateKeyInZone(new Date(), timezone)); const [data, setData] = useState<FinanceData | null>(null); const [error, setError] = useState(""); const [settings, setSettings] = useState(false); const [taxLabel, setTaxLabel] = useState(""); const [taxRate, setTaxRate] = useState(0); const [busy, setBusy] = useState(false); const [revision, setRevision] = useState(0);
  const taxDialogRef = useModalDialog(() => setSettings(false), settings, busy);
  useEffect(() => { fetch(`/api/finance?day=${day}`).then((response) => result<FinanceData>(response)).then((finance) => { setData(finance); setTaxLabel(finance.location.taxLabel); setTaxRate(finance.location.taxRateBps / 100); }).catch((reason) => setError(reason.message)); }, [day, revision]);
  const displayMoney = (cents: number) => money(cents, data?.location.currency || "CAD");
  async function saveTax() { setBusy(true); setError(""); try { await result(await fetch("/api/finance", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ taxLabel, taxRateBps: Math.round(taxRate * 100) }) })); setSettings(false); setRevision((value) => value + 1); } catch (reason) { setError(reason instanceof Error ? reason.message : "Tax settings could not be saved."); } finally { setBusy(false); } }
  return <section className="business-panel finance-panel"><div className="business-toolbar"><div><h2>Payments & closeout</h2><p>Reconcile every tender, tax dollar, tip, and refund.</p></div><div className="finance-actions"><label>Closeout date<input type="date" value={day} onChange={(event) => { setData(null); setDay(event.target.value); }} /></label>{data?.canManage && <button className="secondary-button" onClick={() => setSettings(true)}>Tax settings</button>}</div></div>{error && <p className="inline-error" role="alert">{error}</p>}{!data ? <div className="dashboard-loading" role="status" aria-label="Loading financial ledger"><span /><span /><span /></div> : <><div className="report-metrics finance-metrics"><article><span>Net collected</span><strong>{displayMoney(data.metrics.collectedCents)}</strong><small>{data.metrics.transactionCount} ledger events</small></article><article><span>Payments</span><strong>{displayMoney(data.metrics.paymentsCents)}</strong><small>Before refunds</small></article><article><span>Refunds</span><strong>{displayMoney(data.metrics.refundsCents)}</strong><small>Explicit adjustments</small></article><article><span>Tax recorded</span><strong>{displayMoney(data.metrics.taxCents)}</strong><small>{data.location.taxLabel} at {(data.location.taxRateBps / 100).toFixed(2)}%</small></article></div>
    <div className="finance-grid"><section className="closeout-card"><header><div><h3>Tender reconciliation</h3><p>Compare these totals with your terminal, cash drawer, and transfers.</p></div><strong>{displayMoney(data.metrics.collectedCents)}</strong></header><div className="tender-breakdown">{Object.entries(data.metrics.byMethod).map(([method, amount]) => <div key={method}><span>{methodLabel(method)}</span><strong>{displayMoney(amount)}</strong></div>)}</div></section><section className="closeout-card"><header><div><h3>Today’s ledger</h3><p>Payments and refunds are never overwritten.</p></div></header><div className="ledger-list">{data.events.length ? data.events.map((event) => <div key={event.id}><span className={event.kind}>{event.kind === "payment" ? "+" : "−"}</span><div><strong>{event.petName} · {event.clientName}</strong><small>{methodLabel(event.method)} · {timeInZone(event.occurredAt, timezone)}</small></div><em>{event.kind === "refund" ? "−" : ""}{displayMoney(event.amountCents)}</em></div>) : <div className="report-empty">No payments recorded for this day.</div>}</div></section></div>
    <CloseoutControl key={`${data.day}:${data.closeout?.id || "open"}:${data.closeout?.status || "new"}`} data={data} timezone={timezone} onChanged={() => setRevision((value) => value + 1)} />
    <section className="invoice-table"><header><div><h3>Recent invoices</h3><p>Open any invoice to collect a balance, print a receipt, or refund a payment.</p></div></header><div className="invoice-table-head"><span>Invoice</span><span>Client & pet</span><span>Status</span><span>Total</span><span>Net paid</span><span /></div>{data.invoices.length ? data.invoices.map((invoice) => <button key={invoice.id} onClick={() => onCheckout(invoice.appointmentId)}><span>{invoice.invoiceNumber}</span><span><strong>{invoice.petName}</strong><small>{invoice.clientName}</small></span><span><i className={`invoice-status ${invoice.status}`}>{statusLabel(invoice.status)}</i></span><span>{displayMoney(invoice.totalCents)}</span><span>{displayMoney(invoice.amountPaidCents - invoice.amountRefundedCents)}</span><em>›</em></button>) : <div className="report-empty">Completed checkouts will appear here.</div>}</section></>}
    {settings && <div className="modal-backdrop" onMouseDown={(event) => { if (!busy && event.currentTarget === event.target) setSettings(false); }}><section ref={taxDialogRef} className="business-modal tax-modal" role="dialog" aria-modal="true" aria-label="Tax settings"><header><div><span className="eyebrow">Location settings</span><h2>Sales tax</h2></div><button disabled={busy} onClick={() => setSettings(false)} aria-label="Close tax settings">×</button></header><p>Set the tax your accountant has confirmed for this location. New invoices snapshot this rate; old receipts never change.</p><div className="field-pair"><label>Tax label<input value={taxLabel} onChange={(event) => setTaxLabel(event.target.value)} placeholder="GST/HST" /></label><label>Rate (%)<input type="number" min="0" max="30" step="0.01" value={taxRate} onChange={(event) => setTaxRate(Number(event.target.value))} /></label></div><button className="primary-button wide" disabled={busy} onClick={saveTax}>{busy ? "Saving…" : "Save tax settings"}</button></section></div>}
  </section>;
}

function CloseoutControl({ data, timezone, onChanged }: { data: FinanceData; timezone: string; onChanged: () => void }) {
  const expectedCash = data.metrics.byMethod.cash || 0, [counted, setCounted] = useState(String((data.closeout?.countedCashCents ?? expectedCash) / 100)), [note, setNote] = useState(data.closeout?.note || ""), [reason, setReason] = useState(""), [busy, setBusy] = useState(false), [error, setError] = useState("");
  const display = (cents: number) => money(cents, data.location.currency);
  async function act(action: "close" | "reopen") { setBusy(true); setError(""); try { await result(await fetch("/api/finance", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify(action === "close" ? { action, day: data.day, countedCashCents: Math.round(Number(counted) * 100), note } : { action, day: data.day, reason }) })); onChanged(); } catch (value) { setError(value instanceof Error ? value.message : "Closeout could not be updated."); } finally { setBusy(false); } }
  if (data.closeout?.status === "closed") return <section className={`closeout-snapshot ${data.closeout.drifted ? "drifted" : "closed"}`}><header><div><span className="eyebrow">Closed business day</span><h3>{data.day}</h3><p>Snapshot taken {dateTimeInZone(data.closeout.closedAt, timezone)}</p></div><em>{data.closeout.drifted ? "Ledger changed" : "Balanced snapshot"}</em></header>{data.closeout.drifted && <p className="closeout-warning">Transactions changed after this closeout. Reopen, verify the drawer, and create a replacement snapshot.</p>}<div className="closeout-values"><div><span>Expected cash</span><strong>{display(data.closeout.expectedCashCents)}</strong></div><div><span>Counted cash</span><strong>{display(data.closeout.countedCashCents)}</strong></div><div><span>Cash variance</span><strong>{data.closeout.cashVarianceCents > 0 ? "+" : ""}{display(data.closeout.cashVarianceCents)}</strong></div><div><span>Net collected</span><strong>{display(data.closeout.netCollectedCents)}</strong></div></div>{data.closeout.note && <p className="closeout-note">{data.closeout.note}</p>}{data.canManage && <div className="reopen-row"><input aria-label="Reason to reopen closeout" value={reason} onChange={(event) => setReason(event.target.value)} placeholder="Reason required to reopen" /><button className="secondary-button" disabled={busy || reason.trim().length < 3} onClick={() => void act("reopen")}>{busy ? "Reopening…" : "Reopen closeout"}</button></div>}{error && <p className="inline-error" role="alert">{error}</p>}</section>;
  return <section className="closeout-snapshot open"><header><div><span className="eyebrow">{data.closeout ? "Reopened business day" : "End-of-day control"}</span><h3>Count the cash drawer</h3><p>Freeze a server-calculated snapshot of every tender, refund, tip, and tax entry.</p></div><strong>{display(expectedCash)} expected</strong></header>{data.canManage ? <div className="closeout-form"><label>Counted cash<span className="money-input"><span>{data.location.currency}</span><input type="number" min="0" step="0.01" value={counted} onChange={(event) => setCounted(event.target.value)} /></span></label><label>Closeout note<input value={note} onChange={(event) => setNote(event.target.value)} placeholder="Deposit bag, terminal batch, explanation for variance…" /></label><div><span>Live variance</span><strong>{display(Math.round(Number(counted || 0) * 100) - expectedCash)}</strong></div><button className="primary-button" disabled={busy || !counted} onClick={() => void act("close")}>{busy ? "Closing…" : data.closeout ? "Replace closeout snapshot" : "Close business day"}</button></div> : <p className="books-disclaimer">An owner or manager closes and reopens business days.</p>}{error && <p className="inline-error" role="alert">{error}</p>}</section>;
}

export function FinanceView({ onCheckout, timezone = "America/Toronto" }: { onCheckout: (appointmentId: string) => void; timezone?: string }) {
  const [mode, setMode] = useState<"closeout" | "books">("closeout");
  return <><div className="finance-mode-switch" role="tablist" aria-label="Financial workspace"><button type="button" role="tab" aria-selected={mode === "closeout"} className={mode === "closeout" ? "selected" : ""} onClick={() => setMode("closeout")}>Payments & closeout</button><button type="button" role="tab" aria-selected={mode === "books"} className={mode === "books" ? "selected" : ""} onClick={() => setMode("books")}>Expenses & books</button></div>{mode === "closeout" ? <CloseoutView onCheckout={onCheckout} timezone={timezone} /> : <section className="business-panel finance-panel"><div className="business-toolbar"><div><h2>Expenses & books</h2><p>Cash-basis operating view, tax support, receipt evidence, and accountant-ready exports.</p></div></div><AccountingView /></section>}</>;
}
