"use client";
import { FormEvent, useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import { WeeklyTimesheetsAdmin } from "./weekly-timesheets-admin";

type Person = { id: string; displayName: string; role: string; compensation: null | { payType: "hourly" | "salary"; workerClass: "employee" | "contractor"; hourlyRateCents: number; annualSalaryCents: number; weeklyOvertimeMinutes: number; overtimeMultiplierBps: number; serviceCommissionBps: number; retailCommissionBps: number; overtimeEligible: boolean; effectiveFrom: string } };
type Entry = { id: string; staffId: string; staffName: string; effectiveClockIn: string; effectiveClockOut: string | null; effectiveBreakMinutes: number; paidMinutes: number | null; status: string; source: string; adjusted: boolean };
type WorkforceData = { canManage: boolean; canSeePayroll: boolean; currentStaffId: string; currency: string; disclaimer: string; team: Person[]; states: Array<{ staffId: string; status: string; openEntryId: string | null }>; entries: Entry[] };
type PayrollLine = { id: string; staffName: string; regularMinutes: number; overtimeMinutes: number; regularPayCents: number; overtimePayCents: number; serviceCommissionCents: number; tipsCents: number; grossPayCents: number; payoutCents: number };
type Period = { id: string; startsOn: string; endsOn: string; payDate: string; status: string; currency: string; lines: PayrollLine[] };

const money = (cents: number, currency: string) => new Intl.NumberFormat("en-CA", { style: "currency", currency }).format(cents / 100);
const hours = (minutes: number | null) => minutes === null ? "Open" : `${(minutes / 60).toFixed(2)} h`;
const zonedDate = (value: string, timezone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: timezone, month: "short", day: "numeric" }).format(new Date(value));
const zonedTime = (value: string, timezone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: timezone, hour: "numeric", minute: "2-digit" }).format(new Date(value));
const localInput = (iso: string) => { const d = new Date(iso); d.setMinutes(d.getMinutes() - d.getTimezoneOffset()); return d.toISOString().slice(0, 16); };

export function WorkforceView({ notify, organizationName = "Salon", currency, timezone = "America/Toronto" }: { notify: (message: string) => void; organizationName?: string; currency?: string; timezone?: string }) {
  const [tab, setTab] = useState<"clock" | "timesheets" | "weekly" | "payroll">("clock"); const [data, setData] = useState<WorkforceData | null>(null); const [periods, setPeriods] = useState<Period[]>([]); const [loading, setLoading] = useState(true); const [loadError, setLoadError] = useState(""); const [busy, setBusy] = useState(false); const [breakMinutes, setBreakMinutes] = useState(0); const [editingPay, setEditingPay] = useState<Person | null>(null);
  const fetchData = useCallback(async () => { const response = await fetch("/api/workforce", { cache: "no-store" }); const result = await response.json() as WorkforceData & { error?: string }; if (!response.ok) throw new Error(result.error); let nextPeriods: Period[] = []; if (result.canSeePayroll) { const pay = await fetch("/api/payroll", { cache: "no-store" }); const payData = await pay.json() as { periods?: Period[]; error?: string }; if (!pay.ok) throw new Error(payData.error || "Payroll history is temporarily unavailable."); nextPeriods = payData.periods || []; } return { result, nextPeriods }; }, []);
  const refresh = useCallback(async () => { const next = await fetchData(); setData(next.result); setPeriods(next.nextPeriods); setLoadError(""); }, [fetchData]);
  const retry = useCallback(async () => { setLoading(true); setLoadError(""); try { await refresh(); } catch (reason) { const message = reason instanceof Error ? reason.message : "Workforce data is temporarily unavailable."; setLoadError(message); } finally { setLoading(false); } }, [refresh]);
  useEffect(() => { let cancelled = false; fetchData().then((next) => { if (!cancelled) { setData(next.result); setPeriods(next.nextPeriods); setLoadError(""); } }).catch((reason: Error) => { if (!cancelled) setLoadError(reason.message || "Workforce data is temporarily unavailable."); }).finally(() => { if (!cancelled) setLoading(false); }); return () => { cancelled = true; }; }, [fetchData]);
  const myState = data?.states.find((state) => state.staffId === data.currentStaffId); const clockedIn = myState?.status === "clocked_in"; const submitted = data?.entries.filter((entry) => entry.status === "submitted").length || 0;
  async function action(url: string, method: string, body: Record<string, unknown>) { setBusy(true); try { const response = await fetch(url, { method, headers: { "content-type": "application/json" }, body: JSON.stringify(body) }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "The action could not be completed."); await refresh(); notify("Workforce ledger updated"); return true; } catch (reason) { notify(reason instanceof Error ? reason.message : "The action could not be completed."); return false; } finally { setBusy(false); } }
  if (loading && !data) return <section className="workforce-load-state" role="status" aria-live="polite">Loading workforce records…</section>;
  if (loadError && !data) return <section className="workforce-load-state error" role="alert"><strong>Workforce records could not be loaded.</strong><p>{loadError}</p><button className="secondary-button" onClick={() => void retry()}>Try again</button></section>;
  return <>
    {loadError && <p className="inline-error" role="alert">{loadError} <button onClick={() => void retry()}>Retry</button></p>}
    <div className="workforce-toolbar"><div className="workforce-tabs" role="tablist" aria-label="Workforce sections"><button role="tab" aria-selected={tab === "clock"} className={tab === "clock" ? "active" : ""} onClick={() => setTab("clock")}>My clock</button><button role="tab" aria-selected={tab === "timesheets"} className={tab === "timesheets" ? "active" : ""} onClick={() => setTab("timesheets")}>Punches {submitted > 0 && <b>{submitted}</b>}</button>{data?.canManage && <button role="tab" aria-selected={tab === "weekly"} className={tab === "weekly" ? "active" : ""} onClick={() => setTab("weekly")}>Weekly sheets</button>}{data?.canSeePayroll && <button role="tab" aria-selected={tab === "payroll"} className={tab === "payroll" ? "active" : ""} onClick={() => setTab("payroll")}>Payroll</button>}</div><span>Private · auditable · location scoped</span></div>
    {tab === "clock" ? <div className="workforce-grid"><section className={`clock-card ${clockedIn ? "running" : ""}`}><span className="eyebrow">Personal time clock</span><h2>{clockedIn ? "You’re on the clock." : "Ready when you are."}</h2><p>{clockedIn ? "Your open punch is safely attached to this location." : "Clock in once you’re ready to begin paid work."}</p>{clockedIn && <label>Unpaid break minutes<input type="number" min="0" max="720" value={breakMinutes} onChange={(event) => setBreakMinutes(Number(event.target.value))} /></label>}<button disabled={busy} className="primary-button" onClick={() => void action("/api/workforce", "POST", { action: clockedIn ? "clock_out" : "clock_in", breakMinutes, idempotencyKey: crypto.randomUUID() })}>{clockedIn ? "Clock out" : "Clock in"}</button></section><section className="my-time-card"><header><div><h3>Recent punches</h3><p>Corrections remain visible in the audit history.</p></div></header>{data?.entries.filter((entry) => entry.staffId === data.currentStaffId).slice(0, 8).map((entry) => <article key={entry.id}><time>{zonedDate(entry.effectiveClockIn, timezone)}</time><div><strong>{zonedTime(entry.effectiveClockIn, timezone)} – {entry.effectiveClockOut ? zonedTime(entry.effectiveClockOut, timezone) : "Now"}</strong><small>{entry.effectiveBreakMinutes} min break{entry.adjusted ? " · corrected" : ""}</small></div><b>{hours(entry.paidMinutes)}</b><span className={`time-status ${entry.status}`}>{entry.status}</span></article>)}</section></div>
    : tab === "timesheets" ? <Timesheets data={data} busy={busy} action={action} onPay={setEditingPay} timezone={timezone} />
    : tab === "weekly" ? <WeeklyTimesheetsAdmin notify={notify} organizationName={organizationName} currency={currency || data?.currency} />
    : <Payroll data={data} periods={periods} busy={busy} action={action} />}
    {editingPay && data && <CompensationModal person={editingPay} currency={data.currency} busy={busy} close={() => setEditingPay(null)} save={(values) => action("/api/workforce", "POST", values)} />}
  </>;
}

function Timesheets({ data, busy, action, onPay, timezone }: { data: WorkforceData | null; busy: boolean; action: (url: string, method: string, body: Record<string, unknown>) => Promise<boolean>; onPay: (person: Person) => void; timezone: string }) {
  const [manual, setManual] = useState(false); const [correcting, setCorrecting] = useState<Entry | null>(null);
  return <><section className="timesheet-board"><header><div><h2>Team timesheets</h2><p>Review submitted punches before building payroll.</p></div>{data?.canManage && <button className="primary-button" onClick={() => setManual(true)}>＋ Manual entry</button>}</header><div className="timesheet-head"><span>Team member</span><span>Punch</span><span>Paid</span><span>Status</span><span>Review</span></div>{data?.entries.map((entry) => <article key={entry.id}><div><strong>{entry.staffName}</strong><small>{entry.source}{entry.adjusted ? " · corrected" : ""}</small></div><div><strong>{zonedDate(entry.effectiveClockIn, timezone)}</strong><small>{zonedTime(entry.effectiveClockIn, timezone)} – {entry.effectiveClockOut ? zonedTime(entry.effectiveClockOut, timezone) : "open"} · {entry.effectiveBreakMinutes}m break</small></div><b>{hours(entry.paidMinutes)}</b><span className={`time-status ${entry.status}`}>{entry.status}</span><div className="time-actions">{data.canManage && entry.status === "submitted" && <button disabled={busy} onClick={() => void action("/api/workforce", "PATCH", { action: "approve", entryId: entry.id })}>Approve</button>}{data.canManage && entry.effectiveClockOut && <button onClick={() => setCorrecting(entry)}>Correct</button>}{data.canManage && entry.status !== "void" && <button className="danger" disabled={busy} onClick={() => void action("/api/workforce", "PATCH", { action: "void", entryId: entry.id, reason: "Voided by manager" })}>Void</button>}</div></article>)}</section>{data?.canSeePayroll && <section className="compensation-list"><header><div><h3>Compensation rules</h3><p>Every change starts on an effective date; old rules remain preserved.</p></div></header>{data.team.map((person) => <article key={person.id}><div><strong>{person.displayName}</strong><small>{person.role}</small></div><span>{person.compensation ? person.compensation.payType === "hourly" ? money(person.compensation.hourlyRateCents, data.currency) + "/hr" : money(person.compensation.annualSalaryCents, data.currency) + "/yr" : "Not configured"}</span><span>{person.compensation ? `${(person.compensation.serviceCommissionBps / 100).toFixed(2)}% service commission` : "—"}</span>{data.canManage && <button onClick={() => onPay(person)}>{person.compensation ? "New rate" : "Configure"}</button>}</article>)}</section>}{manual && data && <ManualModal team={data.team} busy={busy} close={() => setManual(false)} save={(values) => action("/api/workforce", "POST", values)} />}{correcting && <CorrectionModal entry={correcting} busy={busy} close={() => setCorrecting(null)} save={(values) => action("/api/workforce", "PATCH", values)} />}</>;
}

function Payroll({ data, periods, busy, action }: { data: WorkforceData | null; periods: Period[]; busy: boolean; action: (url: string, method: string, body: Record<string, unknown>) => Promise<boolean> }) {
  const [open, setOpen] = useState(false); const totals = useMemo(() => periods[0]?.lines.reduce((sum, line) => sum + line.grossPayCents, 0) || 0, [periods]);
  return <><p className="payroll-disclaimer">ⓘ {data?.disclaimer}</p><div className="payroll-metrics"><article><span>Latest gross payroll</span><strong>{money(totals, periods[0]?.currency || data?.currency || "CAD")}</strong><small>{periods[0] ? `${periods[0].startsOn} – ${periods[0].endsOn}` : "No period built"}</small></article><article><span>Time awaiting approval</span><strong>{data?.entries.filter((entry) => entry.status === "submitted").length || 0}</strong><small>Must be cleared before approval</small></article><article><span>Pay runs</span><strong>{periods.length}</strong><small>Immutable snapshots and exports</small></article></div><section className="payroll-board"><header><div><h2>Pay periods</h2><p>Build a weekly or biweekly gross-pay handoff.</p></div>{data?.canManage && <button className="primary-button" onClick={() => setOpen(true)}>＋ Build pay period</button>}</header>{periods.map((period) => <article key={period.id}><header><div><span>{period.startsOn} – {period.endsOn}</span><h3>Pay date {period.payDate}</h3></div><span className={`time-status ${period.status}`}>{period.status}</span><strong>{money(period.lines.reduce((sum, line) => sum + line.grossPayCents, 0), period.currency)}</strong></header><div className="payroll-lines">{period.lines.map((line) => <div key={line.id}><span><strong>{line.staffName}</strong><small>{hours(line.regularMinutes)} regular · {hours(line.overtimeMinutes)} overtime</small></span><span><small>Base + OT</small>{money(line.regularPayCents + line.overtimePayCents, period.currency)}</span><span><small>Commission</small>{money(line.serviceCommissionCents, period.currency)}</span><span><small>Tips</small>{money(line.tipsCents, period.currency)}</span><b>{money(line.grossPayCents, period.currency)} gross</b></div>)}</div><footer><a href={`/api/payroll/export?periodId=${period.id}`}>Export payroll CSV</a>{data?.canManage && period.status === "draft" && <button disabled={busy} onClick={() => void action("/api/payroll", "PATCH", { action: "approve", periodId: period.id })}>Approve snapshot</button>}{data?.canManage && period.status !== "draft" && <button disabled={busy} onClick={() => void action("/api/payroll", "PATCH", { action: "reopen", periodId: period.id, reason: "Reopened for a documented correction" })}>Reopen</button>}</footer></article>)}{!periods.length && <div className="report-empty">Configure compensation, approve time, then build the first period.</div>}</section>{open && <PeriodModal busy={busy} close={() => setOpen(false)} save={(values) => action("/api/payroll", "POST", values)} />}</>;
}

function Modal({ title, children, close, submit, busy }: { title: string; children: React.ReactNode; close: () => void; submit: (event: FormEvent<HTMLFormElement>) => void; busy: boolean }) {
  const dialog = useRef<HTMLFormElement>(null); const titleId = useId();
  useEffect(() => {
    const element = dialog.current; if (!element) return; const previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null;
    const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden";
    const focusable = () => Array.from(element.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]'));
    focusable()[0]?.focus();
    const keydown = (event: KeyboardEvent) => { if (event.key === "Escape" && !busy) { close(); return; } if (event.key !== "Tab") return; const items = focusable(); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
    document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = previousOverflow; previousFocus?.focus(); };
  }, [busy, close]);
  return <div className="modal-backdrop" onMouseDown={(event) => { if (event.currentTarget === event.target && !busy) close(); }}><form ref={dialog} className="checkout-modal workforce-modal" role="dialog" aria-modal="true" aria-labelledby={titleId} onSubmit={submit}><header><div><span className="eyebrow">Workforce ledger</span><h2 id={titleId}>{title}</h2></div><button type="button" disabled={busy} onClick={close} aria-label={`Close ${title}`}>×</button></header>{children}<footer><button type="button" className="secondary-button" disabled={busy} onClick={close}>Cancel</button><button disabled={busy} className="primary-button">{busy ? "Saving…" : "Save"}</button></footer></form></div>;
}
function ManualModal({ team, busy, close, save }: { team: Person[]; busy: boolean; close: () => void; save: (body: Record<string, unknown>) => Promise<boolean> }) { return <Modal title="Add a time entry" busy={busy} close={close} submit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await save({ action: "manual_entry", staffId: f.get("staffId"), clockIn: f.get("clockIn"), clockOut: f.get("clockOut"), breakMinutes: f.get("breakMinutes"), note: f.get("note"), idempotencyKey: crypto.randomUUID() })) close(); }}><label>Team member<select name="staffId" required>{team.map((p) => <option key={p.id} value={p.id}>{p.displayName}</option>)}</select></label><div className="workforce-form-grid"><label>Clock in<input name="clockIn" type="datetime-local" required /></label><label>Clock out<input name="clockOut" type="datetime-local" required /></label></div><label>Unpaid break minutes<input name="breakMinutes" type="number" min="0" defaultValue="0" /></label><label>Note<input name="note" placeholder="Why this was entered manually" /></label></Modal>; }
function CorrectionModal({ entry, busy, close, save }: { entry: Entry; busy: boolean; close: () => void; save: (body: Record<string, unknown>) => Promise<boolean> }) { return <Modal title="Correct time without erasing history" busy={busy} close={close} submit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await save({ action: "adjust", entryId: entry.id, clockIn: f.get("clockIn"), clockOut: f.get("clockOut"), breakMinutes: f.get("breakMinutes"), reason: f.get("reason") })) close(); }}><div className="workforce-form-grid"><label>Correct clock in<input name="clockIn" type="datetime-local" defaultValue={localInput(entry.effectiveClockIn)} required /></label><label>Correct clock out<input name="clockOut" type="datetime-local" defaultValue={entry.effectiveClockOut ? localInput(entry.effectiveClockOut) : ""} required /></label></div><label>Unpaid break minutes<input name="breakMinutes" type="number" min="0" defaultValue={entry.effectiveBreakMinutes} /></label><label>Required reason<textarea name="reason" required placeholder="Explain the correction" /></label></Modal>; }
function CompensationModal({ person, currency, busy, close, save }: { person: Person; currency: string; busy: boolean; close: () => void; save: (body: Record<string, unknown>) => Promise<boolean> }) { const p = person.compensation; return <Modal title={`Compensation · ${person.displayName}`} busy={busy} close={close} submit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await save({ action: "save_compensation", staffId: person.id, payType: f.get("payType"), workerClass: f.get("workerClass"), hourlyRateCents: Math.round(Number(f.get("hourlyRate")) * 100), annualSalaryCents: Math.round(Number(f.get("annualSalary")) * 100), weeklyOvertimeMinutes: Math.round(Number(f.get("overtimeHours")) * 60), overtimeMultiplierBps: Math.round(Number(f.get("overtimeMultiplier")) * 10000), serviceCommissionBps: Math.round(Number(f.get("serviceCommission")) * 100), retailCommissionBps: Math.round(Number(f.get("retailCommission")) * 100), overtimeEligible: f.get("overtimeEligible") === "on", effectiveFrom: f.get("effectiveFrom"), currency })) close(); }}><div className="workforce-form-grid"><label>Worker class<select name="workerClass" defaultValue={p?.workerClass || "employee"}><option value="employee">Employee</option><option value="contractor">Contractor</option></select></label><label>Pay type<select name="payType" defaultValue={p?.payType || "hourly"}><option value="hourly">Hourly</option><option value="salary">Salary</option></select></label><label>Hourly rate ({currency})<input name="hourlyRate" type="number" min="0" step="0.01" defaultValue={(p?.hourlyRateCents || 0) / 100} /></label><label>Annual salary ({currency})<input name="annualSalary" type="number" min="0" step="0.01" defaultValue={(p?.annualSalaryCents || 0) / 100} /></label><label>Weekly OT after hours<input name="overtimeHours" type="number" min="1" step="0.25" defaultValue={(p?.weeklyOvertimeMinutes || 2400) / 60} /></label><label>OT multiplier<input name="overtimeMultiplier" type="number" min="1" step="0.01" defaultValue={(p?.overtimeMultiplierBps || 15000) / 10000} /></label><label>Service commission %<input name="serviceCommission" type="number" min="0" max="100" step="0.01" defaultValue={(p?.serviceCommissionBps || 0) / 100} /></label><label>Retail commission %<input name="retailCommission" type="number" min="0" max="100" step="0.01" defaultValue={(p?.retailCommissionBps || 0) / 100} /></label><label>Effective from<input name="effectiveFrom" type="date" defaultValue={new Date().toISOString().slice(0, 10)} required /></label></div><label className="check-field"><input name="overtimeEligible" type="checkbox" defaultChecked={p?.overtimeEligible ?? true} /> Apply configured overtime rule</label><p className="form-guidance">This creates a new effective-dated rule. It does not erase prior compensation history.</p></Modal>; }
function PeriodModal({ busy, close, save }: { busy: boolean; close: () => void; save: (body: Record<string, unknown>) => Promise<boolean> }) { return <Modal title="Build a gross-pay snapshot" busy={busy} close={close} submit={async (e) => { e.preventDefault(); const f = new FormData(e.currentTarget); if (await save({ startsOn: f.get("startsOn"), endsOn: f.get("endsOn"), payDate: f.get("payDate"), idempotencyKey: crypto.randomUUID() })) close(); }}><p className="form-guidance">Use an exact 7-day or 14-day period. Only approved punches are included.</p><div className="workforce-form-grid"><label>Period starts<input name="startsOn" type="date" required /></label><label>Period ends<input name="endsOn" type="date" required /></label><label>Pay date<input name="payDate" type="date" required /></label></div></Modal>; }
