"use client";

import { useCallback, useEffect, useId, useMemo, useRef, useState } from "react";
import Link from "next/link";
import { useSearchParams } from "next/navigation";

type Pet = { id: string; name: string; species: string; breed: string; weightKg: number | null; dateOfBirth: string; sex: string; color: string; clientNotes: string };
type Appointment = { id: string; petId: string; status: string; startsAt: string; endsAt: string; updatedAt: string; priceEstimateCents: number; currency: string; serviceId: string; serviceName: string; serviceActive: boolean; locationSlug: string; locationName: string; locationActive: boolean; city: string; region: string; timezone: string; staffName: string | null; reportPublished: boolean | null; clientReport: string | null; canCancel: boolean; canReschedule: boolean; changeDeadline: string; cancellationHours: number };
type Vaccine = { id: string; petId: string; vaccineName: string; administeredOn: string; expiresOn: string; veterinarian: string; status: string; originalFilename: string; mimeType: string; expiryState: "expired" | "soon" | "valid" };
type OpenDeposit = { appointmentId: string; petId: string; petName: string; serviceId: string; serviceName: string; locationSlug: string; locationName: string; expiresAt: string; resumePath: string };
type PortalData = { organizationName?: string; organizationSlug?: string; contactEmail?: string; contactPhone?: string; client: { fullName: string; email: string; phone: string; marketingConsent: boolean }; pets: Pet[]; vaccinations: Vaccine[]; appointments: Appointment[]; openDeposits: OpenDeposit[]; sessionExpiresAt: string };
type Slot = { startsAt: string; date: string; timeLabel: string; staff: Array<{ name: string }> };
type Availability = { range: { from: string; through: string; bookingWindowEnd: string; nextFrom: string | null }; dates: Array<{ date: string; slots: Slot[] }> };
type Tab = "home" | "pets" | "vaccines" | "history" | "profile";
const money = (cents: number, currency: string) => new Intl.NumberFormat(currency === "USD" ? "en-US" : "en-CA", { style: "currency", currency, maximumFractionDigits: 0 }).format(cents / 100);
const dateTime = (value: string, timezone: string) => new Intl.DateTimeFormat("en-CA", { timeZone: timezone, weekday: "long", month: "long", day: "numeric", hour: "numeric", minute: "2-digit" }).format(new Date(value));
const shortDay = (day: string) => new Intl.DateTimeFormat("en-CA", { timeZone: "UTC", weekday: "short", month: "short", day: "numeric" }).format(new Date(`${day}T12:00:00Z`));
const title = (value: string) => value.replaceAll("_", " ").replace(/\b\w/g, (letter) => letter.toUpperCase());
function bookingHref(data: PortalData, appointment?: Appointment) {
  const base = data.organizationSlug
    ? appointment?.locationSlug ? `/book/${encodeURIComponent(data.organizationSlug)}/${encodeURIComponent(appointment.locationSlug)}` : `/book/${encodeURIComponent(data.organizationSlug)}`
    : "/";
  if (!appointment) return base;
  const query = new URLSearchParams({ pet: appointment.petId, service: appointment.serviceId });
  return `${base}?${query.toString()}`;
}

export function PortalExperience({ token }: { token: string }) {
  const searchParams = useSearchParams();
  const [data, setData] = useState<PortalData | null>(null); const [tab, setTab] = useState<Tab>("home"); const [error, setError] = useState(""); const [notice, setNotice] = useState(""); const [busy, setBusy] = useState(false);
  const [editingPet, setEditingPet] = useState<Pet | null>(null); const [addingPet, setAddingPet] = useState(false); const [newPet, setNewPet] = useState({ name: "", breed: "" }); const [vaccinePetId, setVaccinePetId] = useState("");
  const [rescheduling, setRescheduling] = useState<Appointment | null>(null); const [availability, setAvailability] = useState<Availability | null>(null); const [availabilityBusy, setAvailabilityBusy] = useState(false); const [selectedStartsAt, setSelectedStartsAt] = useState("");
  const [renewalEmail, setRenewalEmail] = useState(""); const [renewalBusy, setRenewalBusy] = useState(false); const [renewalMessage, setRenewalMessage] = useState(""); const [renewalError, setRenewalError] = useState("");
  const apiBase = token ? `/api/portal/${encodeURIComponent(token)}` : "/api/portal/session";
  const load = useCallback(async () => { const response = await fetch(apiBase); const result = await response.json() as PortalData & { error?: string }; if (!response.ok) throw new Error(result.error || "Portal unavailable."); setData(result); }, [apiBase]);
  useEffect(() => { let cancelled = false; fetch(apiBase).then(async (response) => { const result = await response.json() as PortalData & { error?: string }; if (!response.ok) throw new Error(result.error || "Portal unavailable."); return result; }).then((result) => { if (!cancelled) setData(result); }).catch((reason) => { if (!cancelled) setError(reason.message); }); return () => { cancelled = true; }; }, [apiBase]);
  const upcoming = useMemo(() => data?.appointments.filter((item) => new Date(item.startsAt) >= new Date() && !["cancelled", "completed", "no_show"].includes(item.status)).sort((a,b) => a.startsAt.localeCompare(b.startsAt)) || [], [data]);
  const history = useMemo(() => data?.appointments.filter((item) => !upcoming.some((future) => future.id === item.id)) || [], [data, upcoming]);
  const rebookAppointment = useMemo(() => data?.appointments.find((item) => item.serviceActive && item.locationActive && item.status === "completed") || data?.appointments.find((item) => item.serviceActive && item.locationActive && !["cancelled", "no_show"].includes(item.status)) || data?.appointments.find((item) => item.serviceActive && item.locationActive), [data]);
  function flash(message: string) { setNotice(message); window.setTimeout(() => setNotice(""), 2600); }
  async function action(payload: Record<string, unknown>, message: string) { setBusy(true); setError(""); try { const response = await fetch(apiBase, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify(payload) }); const result = await response.json() as PortalData & { error?: string }; if (!response.ok) throw new Error(result.error || "Your change could not be saved."); setData(result); flash(message); return true; } catch (reason) { setError(reason instanceof Error ? reason.message : "Your change could not be saved."); return false; } finally { setBusy(false); } }
  async function cancel(appointment: Appointment) { if (!window.confirm(`Cancel ${data?.pets.find((pet) => pet.id === appointment.petId)?.name}’s ${appointment.serviceName}?`)) return; await action({ action: "cancel", appointmentId: appointment.id }, "Appointment cancelled"); }
  async function loadReschedulePage(appointment: Appointment, from = "", append = false) {
    setAvailabilityBusy(true); setError("");
    try {
      const query = new URLSearchParams({ appointmentId: appointment.id });
      if (from) query.set("from", from);
      const response = await fetch(`${apiBase}/availability?${query.toString()}`, { cache: "no-store" });
      const result = await response.json() as Availability & { error?: string };
      if (!response.ok) throw new Error(result.error || "Openings unavailable.");
      setAvailability((current) => append && current ? {
        range: result.range,
        dates: [...current.dates, ...result.dates].filter((day, index, rows) => rows.findIndex((candidate) => candidate.date === day.date) === index),
      } : result);
      setSelectedStartsAt((current) => current || result.dates.find((day) => day.slots.length)?.slots[0]?.startsAt || "");
    } catch (reason) {
      setError(reason instanceof Error ? reason.message : "Openings unavailable.");
    } finally {
      setAvailabilityBusy(false);
    }
  }
  async function openReschedule(appointment: Appointment) { setRescheduling(appointment); setAvailability(null); setSelectedStartsAt(""); void loadReschedulePage(appointment); }
  async function uploadVaccine(event: React.FormEvent<HTMLFormElement>) { event.preventDefault(); const form = new FormData(event.currentTarget); setBusy(true); setError(""); try { const response = await fetch(`${apiBase}/vaccinations`, { method: "POST", body: form }); const result = await response.json() as { error?: string }; if (!response.ok) throw new Error(result.error || "Vaccination could not be saved."); await load(); setVaccinePetId(""); flash("Vaccination record submitted for review"); } catch (reason) { setError(reason instanceof Error ? reason.message : "Vaccination could not be saved."); } finally { setBusy(false); } }
  async function removeVaccine(id: string) { if (!window.confirm("Remove this vaccination record?")) return; const response = await fetch(`${apiBase}/vaccinations/${id}`, { method: "DELETE" }); if (response.ok) { await load(); flash("Vaccination removed"); } else { const result = await response.json() as { error?: string }; setError(result.error || "Could not remove vaccination."); } }
  async function requestFreshLink(event: React.FormEvent<HTMLFormElement>) {
    event.preventDefault(); setRenewalBusy(true); setRenewalMessage(""); setRenewalError("");
    try {
      const salonSlug = searchParams.get("salon") || undefined;
      const locationSlug = searchParams.get("location") || undefined;
      const returnTo = searchParams.get("return_to") || undefined;
      const response = await fetch("/api/portal/request-link", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ email: renewalEmail, salonSlug, locationSlug, returnTo }) });
      const result = await response.json() as { message?: string; error?: string; contact?: { phone?: string; email?: string } };
      if (!response.ok) throw new Error(result.error || "A fresh link could not be requested.");
      setRenewalMessage(result.message || "If that email matches a client account, a secure link has been prepared for delivery.");
    } catch (reason) {
      setRenewalError(reason instanceof Error ? reason.message : "A fresh link could not be requested.");
    } finally {
      setRenewalBusy(false);
    }
  }
  if (!data) return <main className="portal-gate"><div className="portal-brand"><span aria-hidden="true">♡</span><strong>Private pet portal</strong></div>{error ? <section className="portal-request"><span>Link unavailable</span><h1>Let’s get you a fresh private link.</h1><p>{error} Enter the email used for booking; for privacy, the response is the same whether or not it matches an account.</p><form onSubmit={requestFreshLink}><label><span>Booking email</span><input type="email" autoComplete="email" required value={renewalEmail} onChange={(event) => setRenewalEmail(event.target.value)} placeholder="you@example.com"/></label>{renewalMessage && <div className="portal-request-message" role="status">{renewalMessage}</div>}{renewalError && <div className="booking-error" role="alert">{renewalError}</div>}<button className="primary-button wide" disabled={renewalBusy}>{renewalBusy ? "Preparing link…" : "Request my fresh private link"}</button></form><Link href={searchParams.get("salon") ? `/book/${encodeURIComponent(searchParams.get("salon")!)}` : "/"}>Return to booking</Link></section> : <section role="status" aria-live="polite"><div className="portal-loader" aria-hidden="true"/><h1>Gathering your pet family…</h1></section>}</main>;
  const firstName = data.client.fullName.split(" ")[0];
  const organizationName = data.organizationName || "Pet care portal";
  return <main className="portal-shell">{notice && <div className="toast" role="status">{notice}</div>}<header className="portal-top"><div className="portal-brand"><span>{organizationName.slice(0, 1).toUpperCase()}</span><strong>{organizationName}</strong></div><div><div className="portal-session-row"><small>Private pet-parent portal</small><form action="/portal/signout" method="post"><button type="submit">Sign out</button></form></div><strong>{data.client.fullName}</strong></div></header><div className="portal-layout"><aside><nav aria-label="Pet portal sections">{[["home","⌂","Overview"],["pets","♡","My pets"],["vaccines","✓","Vaccinations"],["history","↺","Visit history"],["profile","○","My profile"]].map(([key,icon,label]) => <button key={key} aria-current={tab === key ? "page" : undefined} className={tab === key ? "active" : ""} onClick={() => setTab(key as Tab)}><span aria-hidden="true">{icon}</span>{label}</button>)}</nav>{(data.contactPhone || data.contactEmail) && <div className="portal-support"><strong>Need help?</strong>{data.contactPhone && <a href={`tel:${data.contactPhone}`}>{data.contactPhone}</a>}{data.contactEmail && <a href={`mailto:${data.contactEmail}`}>{data.contactEmail}</a>}</div>}<small>Private session expires<br/>{new Intl.DateTimeFormat("en-CA", { timeZone: "UTC" }).format(new Date(data.sessionExpiresAt))}</small></aside><section className="portal-main">{error && <div className="portal-error" role="alert">{error}<button onClick={() => setError("")} aria-label="Dismiss error">×</button></div>}
    {tab === "home" && <><header className="portal-heading"><span className="eyebrow">Your pet family</span><h1>Hi {firstName}, everything’s in one place.</h1><p>Appointments, care notes, and health records—ready when you need them.</p></header><div className="portal-pet-strip">{data.pets.map((pet, index) => <button key={pet.id} onClick={() => { setEditingPet(pet); setTab("pets"); }}><span className={`pet-avatar ${["sage","lilac","gold"][index%3]}`}>{pet.name[0]}</span><div><strong>{pet.name}</strong><small>{pet.breed}</small></div><em>›</em></button>)}</div>{data.openDeposits.length > 0 && <section className="portal-section deposit-recovery"><div className="portal-section-head"><div><h2>Finish securing this opening</h2><p>Your appointment confirms only after the deposit is verified.</p></div></div><div className="portal-appointments">{data.openDeposits.map((deposit) => <article key={deposit.appointmentId}><div className="appointment-ribbon"><span className="portal-status requested">Deposit pending</span><small>{deposit.locationName}</small></div><div className="appointment-main"><span className="pet-avatar coral">{deposit.petName[0]}</span><div><h3>{deposit.petName} · {deposit.serviceName}</h3><p>Secure checkout remains available until {new Intl.DateTimeFormat("en-CA", { hour: "numeric", minute: "2-digit" }).format(new Date(deposit.expiresAt))}.</p><small>If the hold closes, you can rebook with this saved pet profile.</small></div></div><footer><Link className="primary-button" href={deposit.resumePath}>Complete secure deposit</Link></footer></article>)}</div></section>}<section className="portal-section"><div className="portal-section-head"><div><h2>Coming up</h2><p>Only confirmed or requested care appears here.</p></div><Link href={bookingHref(data, rebookAppointment)}>＋ Book another visit</Link></div>{upcoming.length ? <div className="portal-appointments">{upcoming.map((item) => <AppointmentCard key={item.id} item={item} pet={data.pets.find((pet) => pet.id === item.petId)} onCancel={cancel} onReschedule={openReschedule}/>)}</div> : <div className="portal-empty"><span>♡</span><h3>No upcoming visits</h3><p>Whenever they’re ready, the live calendar is waiting.</p><Link href={bookingHref(data, rebookAppointment)}>Find an opening</Link></div>}</section></>}
    {tab === "pets" && <><header className="portal-heading row"><div><span className="eyebrow">Pet profiles</span><h1>The details that make care personal.</h1></div><button onClick={() => setAddingPet(true)}>＋ Add a pet</button></header><div className="portal-pet-grid">{data.pets.map((pet, index) => <article key={pet.id}><span className={`pet-avatar large ${["sage","lilac","gold"][index%3]}`}>{pet.name[0]}</span><h2>{pet.name}</h2><p>{pet.breed}{pet.color ? ` · ${pet.color}` : ""}</p><dl><div><dt>Birthday</dt><dd>{pet.dateOfBirth || "Not added"}</dd></div><div><dt>Weight</dt><dd>{pet.weightKg ? `${pet.weightKg} kg` : "Not added"}</dd></div><div><dt>Sex</dt><dd>{title(pet.sex)}</dd></div></dl><blockquote>{pet.clientNotes || "Add preferences, routines, or anything you want the care team to know."}</blockquote><button onClick={() => setEditingPet({ ...pet })}>Edit profile</button></article>)}</div></>}
    {tab === "vaccines" && <><header className="portal-heading row"><div><span className="eyebrow">Health records</span><h1>Vaccinations, without the paperwork chase.</h1><p>Upload proof once; the salon can verify it before the next visit.</p></div><button onClick={() => setVaccinePetId(data.pets[0]?.id || "")}>＋ Add record</button></header><div className="vaccine-list">{data.vaccinations.length ? data.vaccinations.map((record) => { const pet = data.pets.find((item) => item.id === record.petId); return <article key={record.id}><span className={record.expiryState}>{record.expiryState === "expired" ? "!" : "✓"}</span><div><strong>{record.vaccineName}</strong><small>{pet?.name} · valid until {record.expiresOn}</small><em className={record.status}>{title(record.status)}</em></div><div>{record.originalFilename && <a href={`${apiBase}/vaccinations/${record.id}`} target="_blank" rel="noreferrer">View proof</a>}{record.status !== "verified" && <button onClick={() => removeVaccine(record.id)}>Remove</button>}</div></article>; }) : <div className="portal-empty"><span>✓</span><h3>No vaccination records yet</h3><p>Add expiry dates and optional proof for each pet.</p></div>}</div></>}
    {tab === "history" && <><header className="portal-heading"><span className="eyebrow">Care history</span><h1>Every visit tells their story.</h1><p>Completed appointments and published groomer notes stay close at hand.</p></header><div className="history-list">{history.map((item) => <article key={item.id}><time>{dateTime(item.startsAt,item.timezone)}</time><div><strong>{data.pets.find((pet) => pet.id === item.petId)?.name} · {item.serviceName}</strong><small>{item.locationName} · {item.staffName || "Care team"}</small>{item.reportPublished && item.clientReport && <blockquote>“{item.clientReport}”</blockquote>}</div><span className={`portal-status ${item.status}`}>{title(item.status)}</span><b>{money(item.priceEstimateCents,item.currency)}</b></article>)}</div></>}
    {tab === "profile" && <Profile data={data} busy={busy} onSave={(profile) => action({ action: "profile", ...profile }, "Profile updated")}/>} </section></div>
    {editingPet && <Modal title={`Edit ${editingPet.name}`} onClose={() => setEditingPet(null)}><div className="portal-form-grid"><Field label="Breed" value={editingPet.breed} onChange={(breed) => setEditingPet({...editingPet,breed})}/><Field label="Color" value={editingPet.color} onChange={(color) => setEditingPet({...editingPet,color})}/><Field label="Birthday" type="date" value={editingPet.dateOfBirth} onChange={(dateOfBirth) => setEditingPet({...editingPet,dateOfBirth})}/><Field label="Weight (kg)" type="number" value={editingPet.weightKg ?? ""} onChange={(weightKg) => setEditingPet({...editingPet,weightKg: weightKg ? Number(weightKg) : null})}/><label><span>Sex</span><select value={editingPet.sex} onChange={(e) => setEditingPet({...editingPet,sex:e.target.value})}><option value="unknown">Unknown</option><option value="female">Female</option><option value="male">Male</option></select></label><label className="full"><span>Care preferences</span><textarea value={editingPet.clientNotes} onChange={(e) => setEditingPet({...editingPet,clientNotes:e.target.value})}/></label></div><button className="primary-button wide" disabled={busy} onClick={async () => { if (await action({ action:"pet",...editingPet }, `${editingPet.name}’s profile updated`)) setEditingPet(null); }}>{busy ? "Saving…" : "Save pet profile"}</button></Modal>}
    {addingPet && <Modal title="Add a pet" onClose={() => setAddingPet(false)}><Field label="Pet name" value={newPet.name} onChange={(name) => setNewPet({...newPet,name})}/><Field label="Breed or mix" value={newPet.breed} onChange={(breed) => setNewPet({...newPet,breed})}/><button className="primary-button wide" disabled={busy} onClick={async () => { if (await action({action:"add_pet",...newPet},`${newPet.name} added`)) { setAddingPet(false); setNewPet({name:"",breed:""}); } }}>{busy ? "Adding…" : "Add pet"}</button></Modal>}
    {vaccinePetId && <Modal title="Add vaccination" onClose={() => setVaccinePetId("")}><form onSubmit={uploadVaccine}><label><span>Pet</span><select name="petId" value={vaccinePetId} onChange={(e) => setVaccinePetId(e.target.value)}>{data.pets.map((pet) => <option key={pet.id} value={pet.id}>{pet.name}</option>)}</select></label><Field label="Vaccine" name="vaccineName"/><div className="portal-form-grid"><Field label="Administered" name="administeredOn" type="date"/><Field label="Valid until" name="expiresOn" type="date" required/></div><Field label="Veterinarian or clinic" name="veterinarian"/><label><span>Proof (optional)</span><input name="file" type="file" accept="application/pdf,image/jpeg,image/png,image/webp"/></label><button className="primary-button wide" disabled={busy}>{busy ? "Uploading…" : "Submit for salon review"}</button></form></Modal>}
    {rescheduling && <Modal title={`Reschedule ${data.pets.find((pet) => pet.id === rescheduling.petId)?.name}`} onClose={() => setRescheduling(null)}><p className="modal-copy">Every option is rechecked against the team and floor capacity. Browse the salon’s full booking window without losing your current appointment.</p>{availability ? <>{availability.dates.some((day) => day.slots.length) ? <div className="reschedule-days">{availability.dates.filter((day) => day.slots.length).map((day) => <section key={day.date}><strong>{shortDay(day.date)}</strong><div>{day.slots.map((slot) => <button aria-label={`${shortDay(day.date)} at ${slot.timeLabel}${slot.staff[0]?.name ? ` with ${slot.staff[0].name}` : ""}`} aria-pressed={selectedStartsAt === slot.startsAt} className={selectedStartsAt === slot.startsAt ? "selected" : ""} key={slot.startsAt} onClick={() => setSelectedStartsAt(slot.startsAt)}>{slot.timeLabel}<small>{slot.staff[0]?.name}</small></button>)}</div></section>)}</div> : <div className="portal-empty compact"><h3>No openings in these dates</h3><p>Keep looking—the next page may have availability.</p></div>}{availability.range.nextFrom && <button className="secondary-button wide" disabled={availabilityBusy} onClick={() => void loadReschedulePage(rescheduling, availability.range.nextFrom!, true)}>{availabilityBusy ? "Checking later dates…" : "Show later dates"}</button>}</> : <div className="portal-loader" role="status" aria-label="Loading live openings"/>}<button className="primary-button wide" disabled={busy || availabilityBusy || !selectedStartsAt} onClick={async () => { if (await action({ action:"reschedule", appointmentId:rescheduling.id, startsAt:selectedStartsAt }, "Appointment rescheduled")) setRescheduling(null); }}>{busy ? "Reserving…" : "Confirm new time"}</button></Modal>}
  </main>;
}

function AppointmentCard({ item, pet, onCancel, onReschedule }: { item: Appointment; pet?: Pet; onCancel: (item: Appointment) => void; onReschedule: (item: Appointment) => void }) { return <article><div className="appointment-ribbon"><span className={`portal-status ${item.status}`}>{title(item.status)}</span><small>{item.locationName}</small></div><div className="appointment-main"><span className="pet-avatar coral">{pet?.name[0]}</span><div><h3>{pet?.name} · {item.serviceName}</h3><p>{dateTime(item.startsAt,item.timezone)}</p><small>{item.staffName ? `with ${item.staffName}` : "Care team"} · {item.city}, {item.region}</small></div><strong>{money(item.priceEstimateCents,item.currency)}</strong></div><footer>{item.canReschedule ? <><button onClick={() => onReschedule(item)}>Reschedule</button><button onClick={() => onCancel(item)}>Cancel</button></> : <small>Changes closed {item.cancellationHours} hours before the visit</small>}</footer></article>; }
function Modal({ title: heading, onClose, children }: { title: string; onClose: () => void; children: React.ReactNode }) {
  const dialog = useRef<HTMLElement>(null); const close = useRef(onClose); const titleId = useId();
  useEffect(() => { close.current = onClose; }, [onClose]);
  useEffect(() => {
    const element = dialog.current; if (!element) return; const previousFocus = document.activeElement instanceof HTMLElement ? document.activeElement : null; const previousOverflow = document.body.style.overflow; document.body.style.overflow = "hidden";
    const focusable = () => Array.from(element.querySelectorAll<HTMLElement>('button:not([disabled]), input:not([disabled]), select:not([disabled]), textarea:not([disabled]), a[href]'));
    focusable()[0]?.focus();
    const keydown = (event: KeyboardEvent) => { if (event.key === "Escape") { close.current(); return; } if (event.key !== "Tab") return; const items = focusable(); if (!items.length) return; const first = items[0], last = items[items.length - 1]; if (event.shiftKey && document.activeElement === first) { event.preventDefault(); last.focus(); } else if (!event.shiftKey && document.activeElement === last) { event.preventDefault(); first.focus(); } };
    document.addEventListener("keydown", keydown); return () => { document.removeEventListener("keydown", keydown); document.body.style.overflow = previousOverflow; previousFocus?.focus(); };
  }, []);
  return <div className="portal-modal-backdrop" onMouseDown={(e) => { if (e.currentTarget === e.target) onClose(); }}><section ref={dialog} className="portal-modal" role="dialog" aria-modal="true" aria-labelledby={titleId}><header><h2 id={titleId}>{heading}</h2><button onClick={onClose} aria-label={`Close ${heading}`}>×</button></header>{children}</section></div>;
}
function Field({ label, value, onChange, type="text", name, required=false, disabled=false }: { label: string; value?: string|number; onChange?: (value:string)=>void; type?:string; name?:string; required?:boolean; disabled?:boolean }) { return <label><span>{label}</span><input name={name} required={required} disabled={disabled} type={type} value={value} onChange={onChange ? (e)=>onChange(e.target.value) : undefined}/></label>; }
function Profile({ data, busy, onSave }: { data: PortalData; busy:boolean; onSave:(profile:{fullName:string;phone:string;marketingConsent:boolean})=>void }) { const [profile,setProfile]=useState({fullName:data.client.fullName,phone:data.client.phone,marketingConsent:data.client.marketingConsent}); return <><header className="portal-heading"><span className="eyebrow">Account details</span><h1>Keep the salon in the loop.</h1><p>Your email stays tied to this private portal.</p></header><section className="profile-card"><Field label="Full name" value={profile.fullName} onChange={(fullName)=>setProfile({...profile,fullName})}/><Field label="Email" value={data.client.email} disabled/><Field label="Phone" value={profile.phone} onChange={(phone)=>setProfile({...profile,phone})}/><label className="portal-consent"><input type="checkbox" checked={profile.marketingConsent} onChange={(e)=>setProfile({...profile,marketingConsent:e.target.checked})}/><span><strong>Helpful salon news</strong><small>Offers require this permission. Operational updates may still be provided for booked care.</small></span></label><button className="primary-button" disabled={busy} onClick={()=>onSave(profile)}>{busy?"Saving…":"Save profile"}</button></section></>; }
